AllCops:
  Exclude:
    - 'bin/*'
    - 'spec/spec_helper.rb'
Rails:
  Enabled: true
Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
