AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
Rails:
  Enabled: true
Metrics/LineLength:
  Max: 130
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: nested