Region.create!([
  {state_id: 1, name: "Винницкая", translit: "vynnytskaia", declension: "Винницкой области", region_center: "Винница", center_declension: "Винницы"},
  {state_id: 18, name: "Волынская", translit: "volynskaia", declension: "Волынской области", region_center: "Луцк", center_declension: "Луцка"},
  {state_id: 11, name: "Днепропетровская", translit: "dnepropetrovskaia", declension: "Днепропетровской области", region_center: "Днепропетровск", center_declension: "Днепропетровска"},
  {state_id: 13, name: "Донецкая", translit: "donetskaia", declension: "Донецкой области", region_center: "Донецк", center_declension: "Донецка"},
  {state_id: 2, name: "Житомирская", translit: "zhytomyrskaia", declension: "Житомирской области", region_center: "Житомир", center_declension: "Житомира"},
  {state_id: 22, name: "Закарпатская", translit: "zakarpatskaia", declension: "Закарпатской области", region_center: "Ужгород", center_declension: "Ужгорода"},
  {state_id: 14, name: "Запорожская", translit: "zaporozhskaia", declension: "Запорожской области", region_center: "Запорожье", center_declension: "Запорожья"},
  {state_id: 15, name: "Ивано-Франковская", translit: "yvano-frankovskaia", declension: "Ивано-Франковской области", region_center: "Ивано-Франковск", center_declension: "Ивано-Франковска"},
  {state_id: 10, name: "Киевская", translit: "kyevskaia", declension: "Киевской области", region_center: "Киев", center_declension: "Киева"},
  {state_id: 16, name: "Кировоградская", translit: "kyrovogradskaia", declension: "Кировоградской области", region_center: "Кировоград", center_declension: "Кировограда"},
  {state_id: 17, name: "Луганская", translit: "luganskaia", declension: "Луганской области", region_center: "Луганск", center_declension: "Луганска"},
  {state_id: 5, name: "Львовская", translit: "lvovskaia", declension: "Львовской области", region_center: "Львов", center_declension: "Львова"},
  {state_id: 19, name: "Николаевская", translit: "nykolaevskaia", declension: "Николаевской области", region_center: "Николаев", center_declension: "Николаева"},
  {state_id: 12, name: "Одесская", translit: "odesskaia", declension: "Одесской области", region_center: "Одесса", center_declension: "Одессы"},
  {state_id: 20, name: "Полтавская", translit: "poltavskaia", declension: "Полтавской области", region_center: "Полтава", center_declension: "Полтавы"},
  {state_id: 21, name: "Республика Крым", translit: "respublyka krym", declension: "Республики Крым", region_center: "Республика Крым", center_declension: "Симферополя"},
  {state_id: 9, name: "Ровенская", translit: "rovenskaia", declension: "Ровенской области", region_center: "Ровно", center_declension: "Ровно"},
  {state_id: 8, name: "Сумская", translit: "sumskaia", declension: "Сумской области", region_center: "Сумы", center_declension: "Сум"},
  {state_id: 3, name: "Тернопольская", translit: "ternopolskaia", declension: "Тернопольской области", region_center: "Тернополь", center_declension: "Тернополя"},
  {state_id: 7, name: "Харьковская", translit: "kharkovskaia", declension: "Харьковской области", region_center: "Харьков", center_declension: "Харькова"},
  {state_id: 23, name: "Херсонская", translit: "khersonskaia", declension: "Херсонской области", region_center: "Херсон", center_declension: "Херсона"},
  {state_id: 4, name: "Хмельницкая", translit: "khmelnytskaia", declension: "Хмельницкой области", region_center: "Хмельницкий", center_declension: "Хмельницкого"},
  {state_id: 24, name: "Черкасская", translit: "cherkasskaia", declension: "Черкасской области", region_center: "Черкассы", center_declension: "Черкасс"},
  {state_id: 6, name: "Черниговская", translit: "chernygovskaia", declension: "Черниговской области", region_center: "Чернигов", center_declension: "Чернигова"},
  {state_id: 25, name: "Черновицкая", translit: "chernovytskaia", declension: "Черновицкой области", region_center: "Черновцы", center_declension: "Черновцов"}
])
City.create!([
  {city_id: 597, state_id: 1, name: "Бар", translit: "bar"},
  {city_id: 599, state_id: 1, name: "Бершадь", translit: "bershad"},
  {city_id: 1, state_id: 1, name: "Винница", translit: "vinnica"},
  {city_id: 602, state_id: 1, name: "Гайсин", translit: "gayisin"},
  {city_id: 609, state_id: 1, name: "Гнивань", translit: "gnivan"},
  {city_id: 27, state_id: 1, name: "Жмеринка", translit: "jmerinka"},
  {city_id: 603, state_id: 1, name: "Ильинцы", translit: "ilinciy"},
  {city_id: 30, state_id: 1, name: "Казатин", translit: "kazatin"},
  {city_id: 604, state_id: 1, name: "Калиновка", translit: "kalinovka"},
  {city_id: 31, state_id: 1, name: "Крыжополь", translit: "kriyjopol"},
  {city_id: 644, state_id: 1, name: "Ладыжин", translit: "Ladujun"},
  {city_id: 32, state_id: 1, name: "Липовец", translit: "lipovec"},
  {city_id: 33, state_id: 1, name: "Литин", translit: "litin"},
  {city_id: 34, state_id: 1, name: "Могилев-Подольский", translit: "mogilev-podolskiyi"},
  {city_id: 35, state_id: 1, name: "Мурованые Куриловцы", translit: "murovaniye_kurilovciy"},
  {city_id: 36, state_id: 1, name: "Немиров", translit: "nemirov"},
  {city_id: 37, state_id: 1, name: "Оратов", translit: "jratov"},
  {city_id: 38, state_id: 1, name: "Песчанка", translit: "peschanka"},
  {city_id: 39, state_id: 1, name: "Погребище", translit: "pogrebishe"},
  {city_id: 40, state_id: 1, name: "Теплик", translit: "teplik"},
  {city_id: 42, state_id: 1, name: "Томашполь", translit: "tomashpol"},
  {city_id: 43, state_id: 1, name: "Тростянец", translit: "trostyanec"},
  {city_id: 44, state_id: 1, name: "Тульчин", translit: "tulchin"},
  {city_id: 41, state_id: 1, name: "Тывров", translit: "tiyvrov"},
  {city_id: 45, state_id: 1, name: "Хмельник", translit: "hmelnik"},
  {city_id: 46, state_id: 1, name: "Черновцы", translit: "chernovciy"},
  {city_id: 47, state_id: 1, name: "Чечельник", translit: "chechelnik"},
  {city_id: 48, state_id: 1, name: "Шаргород", translit: "shargorod"},
  {city_id: 49, state_id: 1, name: "Ямполь", translit: "yampol"},
  {city_id: 50, state_id: 18, name: "Владимир-Волынский", translit: "vladimir-voliynskiyi"},
  {city_id: 51, state_id: 18, name: "Горохов", translit: "gorohov"},
  {city_id: 52, state_id: 18, name: "Иваничи", translit: "ivanichi"},
  {city_id: 53, state_id: 18, name: "Камень-Каширский", translit: "kamen-kashirskiyi"},
  {city_id: 54, state_id: 18, name: "Киверцы", translit: "kiverciy"},
  {city_id: 55, state_id: 18, name: "Ковель", translit: "kovel"},
  {city_id: 56, state_id: 18, name: "Локачи", translit: "lokachi"},
  {city_id: 18, state_id: 18, name: "Луцк", translit: "luck"},
  {city_id: 59, state_id: 18, name: "Любешов", translit: "lyubeshov"},
  {city_id: 60, state_id: 18, name: "Любомль", translit: "lyuboml"},
  {city_id: 61, state_id: 18, name: "Маневичи", translit: "manevichi"},
  {city_id: 62, state_id: 18, name: "Нововолынск", translit: "novovoliynsk"},
  {city_id: 63, state_id: 18, name: "Ратно", translit: "ratno"},
  {city_id: 64, state_id: 18, name: "Рожище", translit: "rojishe"},
  {city_id: 65, state_id: 18, name: "Старая Выжевка", translit: "staraya_viyjevka"},
  {city_id: 66, state_id: 18, name: "Турийск", translit: "turiyisk"},
  {city_id: 67, state_id: 18, name: "Шацк", translit: "shack"},
  {city_id: 68, state_id: 11, name: "Апостоловo", translit: "apostolovo"},
  {city_id: 69, state_id: 11, name: "Васильковка", translit: "vasilkovka"},
  {city_id: 70, state_id: 11, name: "Верхнеднепровск", translit: "verhnedneprovsk"},
  {city_id: 71, state_id: 11, name: "Вольногорск", translit: "volnogorsk"},
  {city_id: 72, state_id: 11, name: "Днепродзержинск", translit: "dneprodzerjinsk"},
  {city_id: 11, state_id: 11, name: "Днепропетровск", translit: "dnepropetrovsk"},
  {city_id: 75, state_id: 11, name: "Желтые Воды", translit: "jeltiye_vodiy"},
  {city_id: 76, state_id: 11, name: "Кривой Рог", translit: "krivoyi_rog"},
  {city_id: 78, state_id: 11, name: "Кринички", translit: "krinichki"},
  {city_id: 79, state_id: 11, name: "Магдалиновка", translit: "magdalinovka"},
  {city_id: 80, state_id: 11, name: "Марганец", translit: "marganec"},
  {city_id: 81, state_id: 11, name: "Межевая", translit: "mejevaya"},
  {city_id: 82, state_id: 11, name: "Никополь", translit: "nikopol"},
  {city_id: 83, state_id: 11, name: "Новомосковск", translit: "novomoskovsk"},
  {city_id: 84, state_id: 11, name: "Орджоникидзе", translit: "jrdjonikidze"},
  {city_id: 85, state_id: 11, name: "Павлоград", translit: "pavlograd"},
  {city_id: 86, state_id: 11, name: "Першотравенск", translit: "pershotravensk"},
  {city_id: 87, state_id: 11, name: "Петриковка", translit: "petrikovka"},
  {city_id: 88, state_id: 11, name: "Петропавловка", translit: "petropavlovka"},
  {city_id: 89, state_id: 11, name: "Покровское", translit: "pokrovskoe"},
  {city_id: 90, state_id: 11, name: "Пятихатки", translit: "pyatihatki"},
  {city_id: 91, state_id: 11, name: "Синельниково", translit: "sinelnikovo"},
  {city_id: 92, state_id: 11, name: "Соленое", translit: "solenoe"},
  {city_id: 93, state_id: 11, name: "Софиевка", translit: "sofievka"},
  {city_id: 94, state_id: 11, name: "Терновка", translit: "ternovka"},
  {city_id: 95, state_id: 11, name: "Томаковка", translit: "tomakovka"},
  {city_id: 96, state_id: 11, name: "Царичанка", translit: "carichanka"},
  {city_id: 97, state_id: 11, name: "Широкое", translit: "shirokoe"},
  {city_id: 98, state_id: 11, name: "Юрьевка", translit: "yurevka"},
  {city_id: 607, state_id: 13, name: "Авдеевка", translit: "avdeevka"},
  {city_id: 121, state_id: 13, name: "Александровка", translit: "aleksandrovka"},
  {city_id: 99, state_id: 13, name: "Амвросиевка", translit: "amvrosievka"},
  {city_id: 100, state_id: 13, name: "Артемовск", translit: "artemovsk"},
  {city_id: 101, state_id: 13, name: "Великая Новоселка", translit: "velikaya_novoselka"},
  {city_id: 102, state_id: 13, name: "Волноваха", translit: "volnovaha"},
  {city_id: 103, state_id: 13, name: "Володарское", translit: "volodarskoe"},
  {city_id: 104, state_id: 13, name: "Горловка", translit: "gorlovka"},
  {city_id: 105, state_id: 13, name: "Дебальцево", translit: "debalcevo"},
  {city_id: 106, state_id: 13, name: "Дзержинск", translit: "dzerjinsk"},
  {city_id: 638, state_id: 13, name: "Димитров", translit: "Dimitrov"},
  {city_id: 107, state_id: 13, name: "Доброполье", translit: "dobropole"},
  {city_id: 639, state_id: 13, name: "Докучаевск", translit: "Dokuchaevsk"},
  {city_id: 13, state_id: 13, name: "Донецк", translit: "doneck"},
  {city_id: 109, state_id: 13, name: "Дружковка", translit: "drujkovka"},
  {city_id: 110, state_id: 13, name: "Енакиево", translit: "enakievo"},
  {city_id: 640, state_id: 13, name: "Ждановка", translit: "Jdanovka"},
  {city_id: 111, state_id: 13, name: "Кировское", translit: "kirovskoe"},
  {city_id: 112, state_id: 13, name: "Константиновка", translit: "konstantinovka"},
  {city_id: 113, state_id: 13, name: "Краматорск", translit: "kramatorsk"},
  {city_id: 114, state_id: 13, name: "Красноармейск", translit: "krasnoarmeyisk"},
  {city_id: 115, state_id: 13, name: "Красный Лиман", translit: "krasniyyi_liman"},
  {city_id: 116, state_id: 13, name: "Макеевка", translit: "makeevka"},
  {city_id: 117, state_id: 13, name: "Мангуш", translit: "mangush"},
  {city_id: 119, state_id: 13, name: "Мариуполь", translit: "mariupol"},
  {city_id: 118, state_id: 13, name: "Марьинка", translit: "marinka"},
  {city_id: 120, state_id: 13, name: "Новоазовск", translit: "novoazovsk"},
  {city_id: 641, state_id: 13, name: "Новогродовка", translit: "Novogrodovka"},
  {city_id: 122, state_id: 13, name: "Селидово", translit: "selidovo"},
  {city_id: 123, state_id: 13, name: "Славянск", translit: "slavyansk"},
  {city_id: 124, state_id: 13, name: "Снежное", translit: "snejnoe"},
  {city_id: 125, state_id: 13, name: "Старобешево", translit: "starobeshevo"},
  {city_id: 126, state_id: 13, name: "Тельманово", translit: "telmanovo"},
  {city_id: 127, state_id: 13, name: "Торез", translit: "torez"},
  {city_id: 642, state_id: 13, name: "Угледар", translit: "Ugledar"},
  {city_id: 128, state_id: 13, name: "Харцызск", translit: "harciyzsk"},
  {city_id: 129, state_id: 13, name: "Шахтарск", translit: "shahtarsk"},
  {city_id: 130, state_id: 13, name: "Ясиноватая", translit: "yasinovataya"},
  {city_id: 131, state_id: 2, name: "Андрушевка", translit: "andrushevka"},
  {city_id: 132, state_id: 2, name: "Барановка", translit: "baranovka"},
  {city_id: 133, state_id: 2, name: "Бердичев", translit: "berdichev"},
  {city_id: 134, state_id: 2, name: "Брусилов", translit: "brusilov"},
  {city_id: 135, state_id: 2, name: "Володарск-Волынский", translit: "volodarsk-voliynskiyi"},
  {city_id: 137, state_id: 2, name: "Емильчино", translit: "emilchino"},
  {city_id: 2, state_id: 2, name: "Житомир", translit: "jitomir"},
  {city_id: 140, state_id: 2, name: "Коростень", translit: "korosten"},
  {city_id: 141, state_id: 2, name: "Коростышев", translit: "korostiyshev"},
  {city_id: 142, state_id: 2, name: "Лугины", translit: "luginiy"},
  {city_id: 143, state_id: 2, name: "Любар", translit: "lyubar"},
  {city_id: 144, state_id: 2, name: "Малин", translit: "malin"},
  {city_id: 145, state_id: 2, name: "Народичи", translit: "narodichi"},
  {city_id: 146, state_id: 2, name: "Новоград-Волынский", translit: "novograd-voliynskiyi"},
  {city_id: 147, state_id: 2, name: "Овруч", translit: "jvruch"},
  {city_id: 148, state_id: 2, name: "Олевск", translit: "jlevsk"},
  {city_id: 149, state_id: 2, name: "Попельня", translit: "popelnya"},
  {city_id: 150, state_id: 2, name: "Радомышль", translit: "radomiyshl"},
  {city_id: 606, state_id: 2, name: "Романов", translit: "romanov"},
  {city_id: 151, state_id: 2, name: "Ружин", translit: "rujin"},
  {city_id: 152, state_id: 2, name: "Червоноармейск", translit: "chervonoarmeyisk"},
  {city_id: 153, state_id: 2, name: "Черняхов", translit: "chernyahov"},
  {city_id: 154, state_id: 2, name: "Чуднов", translit: "chudnov"},
  {city_id: 155, state_id: 22, name: "Берегово", translit: "beregovo"},
  {city_id: 156, state_id: 22, name: "Великий Березный", translit: "velikiyi_berezniyyi"},
  {city_id: 157, state_id: 22, name: "Виноградов", translit: "vinogradov"},
  {city_id: 158, state_id: 22, name: "Воловец", translit: "volovec"},
  {city_id: 619, state_id: 22, name: "Драгобрат", translit: "Dragobrat"},
  {city_id: 159, state_id: 22, name: "Иршавa", translit: "irshava"},
  {city_id: 160, state_id: 22, name: "Межгорье", translit: "mejgore"},
  {city_id: 161, state_id: 22, name: "Мукачево", translit: "mukachevo"},
  {city_id: 162, state_id: 22, name: "Перечин", translit: "perechin"},
  {city_id: 163, state_id: 22, name: "Рахов", translit: "rahov"},
  {city_id: 164, state_id: 22, name: "Свалява", translit: "svalyava"},
  {city_id: 165, state_id: 22, name: "Тячев", translit: "tyachev"},
  {city_id: 22, state_id: 22, name: "Ужгород", translit: "ujgorod"},
  {city_id: 168, state_id: 22, name: "Хуст", translit: "hust"},
  {city_id: 169, state_id: 22, name: "Чоп", translit: "chop"},
  {city_id: 191, state_id: 14, name: "Акимовка", translit: "akimovka"},
  {city_id: 170, state_id: 14, name: "Бердянск", translit: "berdyansk"},
  {city_id: 171, state_id: 14, name: "Васильевка", translit: "vasilevka"},
  {city_id: 172, state_id: 14, name: "Великая Белозерка", translit: "velikaya_belozerka"},
  {city_id: 173, state_id: 14, name: "Веселоe", translit: "veseloe"},
  {city_id: 174, state_id: 14, name: "Вольнянск", translit: "volnyansk"},
  {city_id: 175, state_id: 14, name: "Гуляйполe", translit: "gulyayipole"},
  {city_id: 14, state_id: 14, name: "Запорожье", translit: "zaporoje"},
  {city_id: 179, state_id: 14, name: "Каменка-Днепровская", translit: "kamenka-dneprovskaya"},
  {city_id: 180, state_id: 14, name: "Куйбышево", translit: "kuyibiyshevo"},
  {city_id: 28, state_id: 14, name: "Мелитополь", translit: "melitopol"},
  {city_id: 182, state_id: 14, name: "Михайловка", translit: "mihayilovka"},
  {city_id: 183, state_id: 14, name: "Новониколаевка", translit: "novonikolaevka"},
  {city_id: 184, state_id: 14, name: "Орехов", translit: "jrehov"},
  {city_id: 185, state_id: 14, name: "Пологи", translit: "pologi"},
  {city_id: 186, state_id: 14, name: "Приазовское", translit: "priazovskoe"},
  {city_id: 187, state_id: 14, name: "Приморск", translit: "primorsk"},
  {city_id: 188, state_id: 14, name: "Розовка", translit: "rozovka"},
  {city_id: 189, state_id: 14, name: "Токмак", translit: "tokmak"},
  {city_id: 190, state_id: 14, name: "Черниговка", translit: "chernigovka"},
  {city_id: 176, state_id: 14, name: "Энергодар", translit: "yenergodar"},
  {city_id: 192, state_id: 15, name: "Богородчаны", translit: "bogorodchaniy"},
  {city_id: 193, state_id: 15, name: "Болехов", translit: "bolehov"},
  {city_id: 621, state_id: 15, name: "Буковель", translit: "Bukovel"},
  {city_id: 608, state_id: 15, name: "Бурштын", translit: "burshtyn"},
  {city_id: 194, state_id: 15, name: "Верховина", translit: "verhovina"},
  {city_id: 195, state_id: 15, name: "Галич", translit: "galich"},
  {city_id: 196, state_id: 15, name: "Городенка", translit: "gorodenka"},
  {city_id: 197, state_id: 15, name: "Долина", translit: "dolina"},
  {city_id: 15, state_id: 15, name: "Ивано-Франковск", translit: "ivano-frankovsk"},
  {city_id: 199, state_id: 15, name: "Калуш", translit: "kalush"},
  {city_id: 200, state_id: 15, name: "Коломыя", translit: "kolomiyya"},
  {city_id: 201, state_id: 15, name: "Косов", translit: "kosov"},
  {city_id: 202, state_id: 15, name: "Надворная", translit: "nadvornaya"},
  {city_id: 203, state_id: 15, name: "Рогатин", translit: "rogatin"},
  {city_id: 204, state_id: 15, name: "Рожнятов", translit: "rojnyatov"},
  {city_id: 205, state_id: 15, name: "Снятин", translit: "snyatin"},
  {city_id: 207, state_id: 15, name: "Тлумач", translit: "tlumach"},
  {city_id: 206, state_id: 15, name: "Тысменица", translit: "tiysmenica"},
  {city_id: 208, state_id: 15, name: "Яремча", translit: "yaremcha"},
  {city_id: 209, state_id: 10, name: "Барышевка", translit: "bariyshevka"},
  {city_id: 210, state_id: 10, name: "Белая Церковь", translit: "belaya_cerkov"},
  {city_id: 636, state_id: 10, name: "Березань", translit: "berezan"},
  {city_id: 211, state_id: 10, name: "Богуслав", translit: "boguslav"},
  {city_id: 212, state_id: 10, name: "Борисполь", translit: "borispol"},
  {city_id: 213, state_id: 10, name: "Бородянка", translit: "borodyanka"},
  {city_id: 214, state_id: 10, name: "Бровары", translit: "brovariy"},
  {city_id: 612, state_id: 10, name: "Буча", translit: "bucha"},
  {city_id: 215, state_id: 10, name: "Васильков", translit: "vasilkov"},
  {city_id: 217, state_id: 10, name: "Володарка", translit: "volodarka"},
  {city_id: 216, state_id: 10, name: "Вышгород", translit: "viyshgorod"},
  {city_id: 218, state_id: 10, name: "Згуровка", translit: "zgurovka"},
  {city_id: 219, state_id: 10, name: "Иванков", translit: "ivankov"},
  {city_id: 220, state_id: 10, name: "Ирпень", translit: "irpen"},
  {city_id: 221, state_id: 10, name: "Кагарлык", translit: "kagarliyk"},
  {city_id: 10, state_id: 10, name: "Киев", translit: "kiev"},
  {city_id: 648, state_id: 10, name: "Киево-Святошинский", translit: "Kievo-Svyatoshinskiy"},
  {city_id: 223, state_id: 10, name: "Макаров", translit: "makarov"},
  {city_id: 224, state_id: 10, name: "Мироновка", translit: "mironovka"},
  {city_id: 225, state_id: 10, name: "Обухов", translit: "jbuhov"},
  {city_id: 226, state_id: 10, name: "Переяслав-Хмельницкий", translit: "pereyaslav-hmelnickiyi"},
  {city_id: 227, state_id: 10, name: "Полесское", translit: "polesskoe"},
  {city_id: 228, state_id: 10, name: "Ракитное", translit: "rokitnoe"},
  {city_id: 626, state_id: 10, name: "Ржищев", translit: "rzishev"},
  {city_id: 229, state_id: 10, name: "Сквирa", translit: "skvira"},
  {city_id: 230, state_id: 10, name: "Славутич", translit: "slavutich"},
  {city_id: 231, state_id: 10, name: "Ставище", translit: "stavishe"},
  {city_id: 232, state_id: 10, name: "Тараща", translit: "tarasha"},
  {city_id: 233, state_id: 10, name: "Тетиев", translit: "tetiev"},
  {city_id: 234, state_id: 10, name: "Фастов", translit: "fastov"},
  {city_id: 235, state_id: 10, name: "Яготин", translit: "yagotin"},
  {city_id: 252, state_id: 16, name: "Александрия", translit: "aleksandriya"},
  {city_id: 251, state_id: 16, name: "Александровка", translit: "aleksandrovka"},
  {city_id: 236, state_id: 16, name: "Бобринец", translit: "bobrinec"},
  {city_id: 238, state_id: 16, name: "Гайворон", translit: "gayivoron"},
  {city_id: 239, state_id: 16, name: "Голованевск", translit: "golovanevsk"},
  {city_id: 240, state_id: 16, name: "Добровеличковка", translit: "dobrovelichkovka"},
  {city_id: 241, state_id: 16, name: "Долинская", translit: "dolinskaya"},
  {city_id: 242, state_id: 16, name: "Знаменка", translit: "znamenka"},
  {city_id: 16, state_id: 16, name: "Кировоград", translit: "kirovograd"},
  {city_id: 245, state_id: 16, name: "Компанеевка", translit: "kompaneevka"},
  {city_id: 246, state_id: 16, name: "Малая Виска", translit: "malaya_viska"},
  {city_id: 247, state_id: 16, name: "Новгородкa", translit: "novgorodka"},
  {city_id: 248, state_id: 16, name: "Новоархангельск", translit: "novoarhangelsk"},
  {city_id: 249, state_id: 16, name: "Новомиргород", translit: "novomirgorod"},
  {city_id: 250, state_id: 16, name: "Новоукраинка", translit: "novoukrainka"},
  {city_id: 237, state_id: 16, name: "Ольшанка", translit: "olshanka"},
  {city_id: 253, state_id: 16, name: "Онуфриевка", translit: "jnufrievka"},
  {city_id: 254, state_id: 16, name: "Петрово", translit: "petrovo"},
  {city_id: 255, state_id: 16, name: "Светловодск", translit: "svetlovodsk"},
  {city_id: 256, state_id: 16, name: "Ульяновка", translit: "ulyanovka"},
  {city_id: 257, state_id: 16, name: "Устиновка", translit: "ustinovka"},
  {city_id: 258, state_id: 17, name: "Алчевск", translit: "alchevsk"},
  {city_id: 259, state_id: 17, name: "Антрацит", translit: "antracit"},
  {city_id: 260, state_id: 17, name: "Беловодск", translit: "belovodsk"},
  {city_id: 261, state_id: 17, name: "Белокуракинo", translit: "belokurakino"},
  {city_id: 262, state_id: 17, name: "Брянка", translit: "bryanka"},
  {city_id: 263, state_id: 17, name: "Кировск", translit: "kirovsk"},
  {city_id: 264, state_id: 17, name: "Краснодон", translit: "krasnodon"},
  {city_id: 265, state_id: 17, name: "Красный Луч", translit: "krasniyyi_luch"},
  {city_id: 266, state_id: 17, name: "Кременная", translit: "kremennaya"},
  {city_id: 267, state_id: 17, name: "Лисичанск", translit: "lisichansk"},
  {city_id: 17, state_id: 17, name: "Луганск", translit: "lugansk"},
  {city_id: 269, state_id: 17, name: "Лутугино", translit: "lutugino"},
  {city_id: 270, state_id: 17, name: "Марковка", translit: "markovka"},
  {city_id: 271, state_id: 17, name: "Меловое", translit: "melovoe"},
  {city_id: 272, state_id: 17, name: "Новоайдар", translit: "novoayidar"},
  {city_id: 273, state_id: 17, name: "Новопсков", translit: "novopskov"},
  {city_id: 274, state_id: 17, name: "Первомайск", translit: "pervomayisk"},
  {city_id: 275, state_id: 17, name: "Перевальск", translit: "perevalsk"},
  {city_id: 276, state_id: 17, name: "Попасная", translit: "popasnaya"},
  {city_id: 277, state_id: 17, name: "Ровеньки", translit: "rovenki"},
  {city_id: 278, state_id: 17, name: "Рубежное", translit: "rubejnoe"},
  {city_id: 279, state_id: 17, name: "Сватовo", translit: "svatovo"},
  {city_id: 280, state_id: 17, name: "Свердловск", translit: "sverdlovsk"},
  {city_id: 281, state_id: 17, name: "Северодонецк", translit: "severodoneck"},
  {city_id: 282, state_id: 17, name: "Славяносербск", translit: "slavyanoserbsk"},
  {city_id: 283, state_id: 17, name: "Станично-Луганское", translit: "stanichno-luganskoe"},
  {city_id: 284, state_id: 17, name: "Старобельск", translit: "starobelsk"},
  {city_id: 285, state_id: 17, name: "Стаханов", translit: "stahanov"},
  {city_id: 286, state_id: 17, name: "Троицкое", translit: "troickoe"},
  {city_id: 287, state_id: 5, name: "Борислав", translit: "borislav"},
  {city_id: 288, state_id: 5, name: "Броды", translit: "brodiy"},
  {city_id: 289, state_id: 5, name: "Буск", translit: "busk"},
  {city_id: 290, state_id: 5, name: "Городок", translit: "gorodok"},
  {city_id: 291, state_id: 5, name: "Дрогобыч", translit: "drogobiych"},
  {city_id: 292, state_id: 5, name: "Жидачов", translit: "jidachov"},
  {city_id: 293, state_id: 5, name: "Жолква", translit: "jovkva"},
  {city_id: 294, state_id: 5, name: "Золочев", translit: "zolochev"},
  {city_id: 295, state_id: 5, name: "Каменка-Бугская", translit: "kamenka-bugskaya"},
  {city_id: 5, state_id: 5, name: "Львов", translit: "lvov"},
  {city_id: 646, state_id: 5, name: "Моршин", translit: "Morshun"},
  {city_id: 298, state_id: 5, name: "Мостиска", translit: "mostiska"},
  {city_id: 297, state_id: 5, name: "Николаев", translit: "nikolaev"},
  {city_id: 632, state_id: 5, name: "Новий Роздол", translit: "noviy-rozdil"},
  {city_id: 299, state_id: 5, name: "Перемышляны", translit: "peremiyshlyaniy"},
  {city_id: 300, state_id: 5, name: "Пустомыты", translit: "pustomiytiy"},
  {city_id: 301, state_id: 5, name: "Радехов", translit: "radehov"},
  {city_id: 302, state_id: 5, name: "Самбор", translit: "sambor"},
  {city_id: 303, state_id: 5, name: "Сколе", translit: "skole"},
  {city_id: 304, state_id: 5, name: "Сокаль", translit: "sokal"},
  {city_id: 614, state_id: 5, name: "Сосновка", translit: "sosnovka"},
  {city_id: 305, state_id: 5, name: "Старый Самбор", translit: "stariyyi_sambor"},
  {city_id: 306, state_id: 5, name: "Стрый", translit: "striyyi"},
  {city_id: 307, state_id: 5, name: "Трускавец", translit: "truskavec"},
  {city_id: 308, state_id: 5, name: "Турка", translit: "turka"},
  {city_id: 309, state_id: 5, name: "Червоноград", translit: "chervonograd"},
  {city_id: 310, state_id: 5, name: "Яворов", translit: "yavorov"},
  {city_id: 311, state_id: 19, name: "Арбузинка", translit: "arbuzinka"},
  {city_id: 312, state_id: 19, name: "Баштанка", translit: "bashtanka"},
  {city_id: 313, state_id: 19, name: "Березанка", translit: "berezanka"},
  {city_id: 314, state_id: 19, name: "Березнеговатое", translit: "bereznegovatoe"},
  {city_id: 315, state_id: 19, name: "Братское", translit: "bratskoe"},
  {city_id: 316, state_id: 19, name: "Веселиново", translit: "veselinovo"},
  {city_id: 317, state_id: 19, name: "Вознесенск", translit: "voznesensk"},
  {city_id: 318, state_id: 19, name: "Врадиевка", translit: "vradievka"},
  {city_id: 319, state_id: 19, name: "Доманевка", translit: "domanevka"},
  {city_id: 320, state_id: 19, name: "Еланец", translit: "elanec"},
  {city_id: 321, state_id: 19, name: "Жовтневый район", translit: "jovtneviyyi_rayion"},
  {city_id: 322, state_id: 19, name: "Казанка", translit: "kazanka"},
  {city_id: 613, state_id: 19, name: "Коблево", translit: "Koblevo"},
  {city_id: 323, state_id: 19, name: "Кривое Озеро", translit: "krivoe_jzero"},
  {city_id: 19, state_id: 19, name: "Николаев", translit: "nikolaev"},
  {city_id: 327, state_id: 19, name: "Новая Одесса", translit: "novaya_jdessa"},
  {city_id: 326, state_id: 19, name: "Новый Буг", translit: "noviyyi_bug"},
  {city_id: 328, state_id: 19, name: "Очаков", translit: "jchakov"},
  {city_id: 329, state_id: 19, name: "Первомайск", translit: "pervomayisk"},
  {city_id: 330, state_id: 19, name: "Снигиревка", translit: "snigirevka"},
  {city_id: 331, state_id: 19, name: "Южноукраинск", translit: "yujnoukrainsk"},
  {city_id: 332, state_id: 12, name: "Ананьев", translit: "ananev"},
  {city_id: 333, state_id: 12, name: "Арциз", translit: "arciz"},
  {city_id: 334, state_id: 12, name: "Балта", translit: "balta"},
  {city_id: 336, state_id: 12, name: "Белгород-Днестровский", translit: "belgorod-dnestrovskiyi"},
  {city_id: 337, state_id: 12, name: "Беляевка", translit: "belyaevka"},
  {city_id: 335, state_id: 12, name: "Березовка", translit: "berezovka"},
  {city_id: 338, state_id: 12, name: "Болград", translit: "bolgrad"},
  {city_id: 339, state_id: 12, name: "Великая Михайловка", translit: "velikaya_mihayilovka"},
  {city_id: 625, state_id: 12, name: "Затока", translit: "Zatoka"},
  {city_id: 340, state_id: 12, name: "Ивановка", translit: "ivanovka"},
  {city_id: 341, state_id: 12, name: "Измаил", translit: "izmail"},
  {city_id: 342, state_id: 12, name: "Ильичевск", translit: "ilichevsk"},
  {city_id: 343, state_id: 12, name: "Килия", translit: "kiliya"},
  {city_id: 344, state_id: 12, name: "Кодыма", translit: "kodiyma"},
  {city_id: 345, state_id: 12, name: "Коминтерновское", translit: "kominternovskoe"},
  {city_id: 346, state_id: 12, name: "Котовск", translit: "kotovsk"},
  {city_id: 347, state_id: 12, name: "Красные Окны", translit: "krasniye_jkniy"},
  {city_id: 348, state_id: 12, name: "Любашевка", translit: "lyubashevka"},
  {city_id: 349, state_id: 12, name: "Николаевка", translit: "nikolaevka"},
  {city_id: 350, state_id: 12, name: "Овидиополь", translit: "jvidiopol"},
  {city_id: 12, state_id: 12, name: "Одесса", translit: "odessa"},
  {city_id: 353, state_id: 12, name: "Раздельная", translit: "razdelnaya"},
  {city_id: 352, state_id: 12, name: "Рени", translit: "reni"},
  {city_id: 354, state_id: 12, name: "Саврань", translit: "savran"},
  {city_id: 355, state_id: 12, name: "Сарата", translit: "sarata"},
  {city_id: 356, state_id: 12, name: "Тарутино", translit: "tarutino"},
  {city_id: 357, state_id: 12, name: "Татарбунари", translit: "tatarbunari"},
  {city_id: 635, state_id: 12, name: "Теплодар", translit: "teplodar"},
  {city_id: 358, state_id: 12, name: "Фрунзовка", translit: "frunzovka"},
  {city_id: 359, state_id: 12, name: "Ширяево", translit: "shiryaevo"},
  {city_id: 643, state_id: 12, name: "Южный", translit: "Yujnuy"},
  {city_id: 360, state_id: 20, name: "Великая Багачка", translit: "velikaya_bagachka"},
  {city_id: 361, state_id: 20, name: "Гадяч", translit: "gadyach"},
  {city_id: 362, state_id: 20, name: "Глобино", translit: "globino"},
  {city_id: 363, state_id: 20, name: "Гребенка", translit: "grebenka"},
  {city_id: 364, state_id: 20, name: "Диканька", translit: "dikanka"},
  {city_id: 365, state_id: 20, name: "Зеньков", translit: "zenkov"},
  {city_id: 366, state_id: 20, name: "Карловка", translit: "karlovka"},
  {city_id: 367, state_id: 20, name: "Кобеляки", translit: "kobelyaki"},
  {city_id: 368, state_id: 20, name: "Козельщина", translit: "kozelshina"},
  {city_id: 369, state_id: 20, name: "Комсомольск", translit: "komsomolsk"},
  {city_id: 370, state_id: 20, name: "Котельва", translit: "kotelva"},
  {city_id: 605, state_id: 20, name: "Кременчуг", translit: "kremenchug"},
  {city_id: 373, state_id: 20, name: "Лохвица", translit: "lohvica"},
  {city_id: 374, state_id: 20, name: "Лубны", translit: "lubniy"},
  {city_id: 375, state_id: 20, name: "Машевка", translit: "mashevka"},
  {city_id: 376, state_id: 20, name: "Миргород", translit: "mirgorod"},
  {city_id: 377, state_id: 20, name: "Новые Санжары", translit: "noviye_sanjariy"},
  {city_id: 378, state_id: 20, name: "Оржица", translit: "jrjica"},
  {city_id: 379, state_id: 20, name: "Пирятин", translit: "piryatin"},
  {city_id: 20, state_id: 20, name: "Полтава", translit: "poltava"},
  {city_id: 382, state_id: 20, name: "Решетиловка", translit: "reshetilovka"},
  {city_id: 383, state_id: 20, name: "Семеновка", translit: "semenovka"},
  {city_id: 384, state_id: 20, name: "Хорол", translit: "horol"},
  {city_id: 385, state_id: 20, name: "Чернухи", translit: "chernuhi"},
  {city_id: 386, state_id: 20, name: "Чутово", translit: "chutovo"},
  {city_id: 387, state_id: 20, name: "Шишаки", translit: "shishaki"},
  {city_id: 618, state_id: 21, name: "Алупка", translit: "Alupka"},
  {city_id: 570, state_id: 21, name: "Алушта", translit: "alushta"},
  {city_id: 583, state_id: 21, name: "Бахчисарай", translit: "bahchisarayi"},
  {city_id: 596, state_id: 21, name: "Белогорск", translit: "belogorsk"},
  {city_id: 620, state_id: 21, name: "Гурзуф", translit: "Gurzuf"},
  {city_id: 600, state_id: 21, name: "Джанкой", translit: "djankoyi"},
  {city_id: 589, state_id: 21, name: "Евпатория", translit: "evpatoriya"},
  {city_id: 29, state_id: 21, name: "Керчь", translit: "kerch"},
  {city_id: 598, state_id: 21, name: "Кировское", translit: "kirovskoe"},
  {city_id: 616, state_id: 21, name: "Коктебель", translit: "Koktebel"},
  {city_id: 595, state_id: 21, name: "Красногвардейское", translit: "krasnogvardeyiskoe"},
  {city_id: 585, state_id: 21, name: "Красноперекопск", translit: "krasnoperekopsk"},
  {city_id: 586, state_id: 21, name: "Ленино", translit: "lenino"},
  {city_id: 627, state_id: 21, name: "Мисхор", translit: "Mishor"},
  {city_id: 571, state_id: 21, name: "Нижнегорский", translit: "nijnegorskiyi"},
  {city_id: 630, state_id: 21, name: "Николаевка", translit: "Nikolayevka"},
  {city_id: 591, state_id: 21, name: "Первомайское", translit: "pervomayiskoe"},
  {city_id: 582, state_id: 21, name: "Раздольное", translit: "razdolnoe"},
  {city_id: 584, state_id: 21, name: "Саки", translit: "saki"},
  {city_id: 593, state_id: 21, name: "Севастополь", translit: "sevastopol"},
  {city_id: 21, state_id: 21, name: "Симферополь", translit: "simferopol"},
  {city_id: 587, state_id: 21, name: "Советский", translit: "sovetskiyi"},
  {city_id: 588, state_id: 21, name: "Судак", translit: "sudak"},
  {city_id: 26, state_id: 21, name: "Феодосия", translit: "feodosiya"},
  {city_id: 592, state_id: 21, name: "Черноморское", translit: "chernomorskoe"},
  {city_id: 594, state_id: 21, name: "Ялта", translit: "yalta"},
  {city_id: 388, state_id: 9, name: "Березно", translit: "berezno"},
  {city_id: 389, state_id: 9, name: "Владимирец", translit: "vladimirec"},
  {city_id: 390, state_id: 9, name: "Гоща", translit: "gosha"},
  {city_id: 391, state_id: 9, name: "Демидовка", translit: "demidovka"},
  {city_id: 392, state_id: 9, name: "Дубно", translit: "dubno"},
  {city_id: 393, state_id: 9, name: "Дубровица", translit: "dubrovica"},
  {city_id: 394, state_id: 9, name: "Заречное", translit: "zarechnoe"},
  {city_id: 395, state_id: 9, name: "Здолбунов", translit: "zdolbunov"},
  {city_id: 396, state_id: 9, name: "Корец", translit: "korec"},
  {city_id: 397, state_id: 9, name: "Костополь", translit: "kostopol"},
  {city_id: 398, state_id: 9, name: "Кузнецовск", translit: "kuznecovsk"},
  {city_id: 399, state_id: 9, name: "Млынов", translit: "mliynov"},
  {city_id: 400, state_id: 9, name: "Острог", translit: "jstrog"},
  {city_id: 401, state_id: 9, name: "Радивилов", translit: "radivilov"},
  {city_id: 404, state_id: 9, name: "Ракитное", translit: "rokitnoe"},
  {city_id: 9, state_id: 9, name: "Ровно", translit: "rovno"},
  {city_id: 405, state_id: 9, name: "Сарны", translit: "sarniy"},
  {city_id: 416, state_id: 8, name: "Ахтырка", translit: "ahtiyrka"},
  {city_id: 406, state_id: 8, name: "Белополье", translit: "belopole"},
  {city_id: 407, state_id: 8, name: "Бурынь", translit: "buriyn"},
  {city_id: 408, state_id: 8, name: "Великая Писаревка", translit: "velikaya_pisarevka"},
  {city_id: 409, state_id: 8, name: "Глухов", translit: "gluhov"},
  {city_id: 410, state_id: 8, name: "Конотоп", translit: "konotop"},
  {city_id: 411, state_id: 8, name: "Краснополье", translit: "krasnopole"},
  {city_id: 412, state_id: 8, name: "Кролевец", translit: "krolevec"},
  {city_id: 413, state_id: 8, name: "Лебедин", translit: "lebedin"},
  {city_id: 414, state_id: 8, name: "Липовая Долина", translit: "lipovaya_dolina"},
  {city_id: 415, state_id: 8, name: "Недригайлов", translit: "nedrigayilov"},
  {city_id: 417, state_id: 8, name: "Путивль", translit: "putivl"},
  {city_id: 418, state_id: 8, name: "Ромны", translit: "romniy"},
  {city_id: 419, state_id: 8, name: "Середина-Буда", translit: "seredina-buda"},
  {city_id: 8, state_id: 8, name: "Сумы", translit: "sumiy"},
  {city_id: 422, state_id: 8, name: "Тростянец", translit: "trostyanec"},
  {city_id: 423, state_id: 8, name: "Шостка", translit: "shostka"},
  {city_id: 424, state_id: 8, name: "Ямполь", translit: "yampol"},
  {city_id: 425, state_id: 3, name: "Бережаны", translit: "berejaniy"},
  {city_id: 426, state_id: 3, name: "Борщев", translit: "borshev"},
  {city_id: 427, state_id: 3, name: "Бучач", translit: "buchach"},
  {city_id: 428, state_id: 3, name: "Гусятин", translit: "gusyatin"},
  {city_id: 429, state_id: 3, name: "Залещики", translit: "zaleshiki"},
  {city_id: 430, state_id: 3, name: "Збараж", translit: "zbaraj"},
  {city_id: 431, state_id: 3, name: "Зборов", translit: "zborov"},
  {city_id: 432, state_id: 3, name: "Козова", translit: "kozova"},
  {city_id: 433, state_id: 3, name: "Кременец", translit: "kremenec"},
  {city_id: 434, state_id: 3, name: "Лановцы", translit: "lanovciy"},
  {city_id: 435, state_id: 3, name: "Монастыриска", translit: "monastiyriska"},
  {city_id: 436, state_id: 3, name: "Подволочиск", translit: "podvolochinsk"},
  {city_id: 437, state_id: 3, name: "Подгайцы", translit: "podgayiciy"},
  {city_id: 438, state_id: 3, name: "Теребовля", translit: "terebovlya"},
  {city_id: 3, state_id: 3, name: "Тернополь", translit: "ternopol"},
  {city_id: 441, state_id: 3, name: "Чертков", translit: "chertkov"},
  {city_id: 442, state_id: 3, name: "Шумское", translit: "shumskoe"},
  {city_id: 443, state_id: 7, name: "Балаклея", translit: "balakleya"},
  {city_id: 444, state_id: 7, name: "Барвенково", translit: "barvenkovo"},
  {city_id: 445, state_id: 7, name: "Близнюки", translit: "bliznyuki"},
  {city_id: 446, state_id: 7, name: "Богодухов", translit: "bogoduhov"},
  {city_id: 447, state_id: 7, name: "Боровая", translit: "borovaya"},
  {city_id: 448, state_id: 7, name: "Валки", translit: "valki"},
  {city_id: 449, state_id: 7, name: "Великий Бурлук", translit: "velikiyi_burluk"},
  {city_id: 450, state_id: 7, name: "Волчанск", translit: "volchansk"},
  {city_id: 451, state_id: 7, name: "Двуреченское", translit: "dvurechenskoe"},
  {city_id: 452, state_id: 7, name: "Дергачи", translit: "dergachi"},
  {city_id: 453, state_id: 7, name: "Зачепиловка", translit: "zachepilovka"},
  {city_id: 454, state_id: 7, name: "Змиев", translit: "zmiev"},
  {city_id: 455, state_id: 7, name: "Золочев", translit: "zolochev"},
  {city_id: 456, state_id: 7, name: "Изюм", translit: "izyum"},
  {city_id: 457, state_id: 7, name: "Кегичевка", translit: "kegichevka"},
  {city_id: 458, state_id: 7, name: "Коломак", translit: "kolomak"},
  {city_id: 459, state_id: 7, name: "Красноград", translit: "krasnograd"},
  {city_id: 460, state_id: 7, name: "Краснокутск", translit: "krasnokutsk"},
  {city_id: 461, state_id: 7, name: "Купянск", translit: "kupyansk"},
  {city_id: 462, state_id: 7, name: "Лозовая", translit: "lozovaya"},
  {city_id: 634, state_id: 7, name: "Люботин", translit: "lubotun"},
  {city_id: 463, state_id: 7, name: "Новая Водолага", translit: "novaya_vodolaga"},
  {city_id: 464, state_id: 7, name: "Первомайский", translit: "pervomayiskiyi"},
  {city_id: 465, state_id: 7, name: "Печенеги", translit: "pechenegi"},
  {city_id: 466, state_id: 7, name: "Сахновщина", translit: "sahnovshina"},
  {city_id: 7, state_id: 7, name: "Харьков", translit: "harkov"},
  {city_id: 469, state_id: 7, name: "Чугуев", translit: "chuguev"},
  {city_id: 470, state_id: 7, name: "Шевченково", translit: "shevchenkovo"},
  {city_id: 472, state_id: 23, name: "Белозерка", translit: "belozerka"},
  {city_id: 471, state_id: 23, name: "Берислав", translit: "berislav"},
  {city_id: 474, state_id: 23, name: "Великая Александровка", translit: "velikaya_aleksandrovka"},
  {city_id: 473, state_id: 23, name: "Великая Лепетиха", translit: "velikaya_lepetiha"},
  {city_id: 475, state_id: 23, name: "Верхний Рогачик", translit: "verhniyi_rogachik"},
  {city_id: 476, state_id: 23, name: "Высокополье", translit: "viysokopole"},
  {city_id: 477, state_id: 23, name: "Геническ", translit: "genichesk"},
  {city_id: 478, state_id: 23, name: "Голая Пристань", translit: "golaya_pristan"},
  {city_id: 479, state_id: 23, name: "Горностаевка", translit: "gornostaevka"},
  {city_id: 624, state_id: 23, name: "Железный Порт", translit: "Zelezny Port"},
  {city_id: 480, state_id: 23, name: "Ивановка", translit: "ivanovka"},
  {city_id: 481, state_id: 23, name: "Каланчак", translit: "kalanchak"},
  {city_id: 482, state_id: 23, name: "Каховка", translit: "kahovka"},
  {city_id: 483, state_id: 23, name: "Нижние Серогозы", translit: "nijnie_serogoziy"},
  {city_id: 484, state_id: 23, name: "Новая Каховка", translit: "novaya_kahovka"},
  {city_id: 485, state_id: 23, name: "Нововоронцовка", translit: "novovoroncovka"},
  {city_id: 486, state_id: 23, name: "Новотроицкое", translit: "novotroickoe"},
  {city_id: 487, state_id: 23, name: "Скадовск", translit: "skadovsk"},
  {city_id: 23, state_id: 23, name: "Херсон", translit: "herson"},
  {city_id: 489, state_id: 23, name: "Цюрупинск", translit: "cyurupinsk"},
  {city_id: 490, state_id: 23, name: "Чаплинка", translit: "chaplinka"},
  {city_id: 491, state_id: 4, name: "Белогорье", translit: "belogore"},
  {city_id: 492, state_id: 4, name: "Виньковцы", translit: "vinkovciy"},
  {city_id: 493, state_id: 4, name: "Волочиск", translit: "volochinsk"},
  {city_id: 494, state_id: 4, name: "Городок", translit: "gorodok"},
  {city_id: 495, state_id: 4, name: "Деражня", translit: "derajnya"},
  {city_id: 496, state_id: 4, name: "Дунаевцы", translit: "dunaevciy"},
  {city_id: 497, state_id: 4, name: "Изяслав", translit: "izyaslav"},
  {city_id: 498, state_id: 4, name: "Каменец-Подольский", translit: "kamenec-podolskiyi"},
  {city_id: 499, state_id: 4, name: "Красилов", translit: "krasilov"},
  {city_id: 500, state_id: 4, name: "Летичев", translit: "letichev"},
  {city_id: 501, state_id: 4, name: "Нетешин", translit: "neteshin"},
  {city_id: 502, state_id: 4, name: "Новая Ушица", translit: "novaya_ushica"},
  {city_id: 503, state_id: 4, name: "Полонное", translit: "polonnoe"},
  {city_id: 504, state_id: 4, name: "Славута", translit: "slavuta"},
  {city_id: 506, state_id: 4, name: "Старая Синява", translit: "staraya_sinyava"},
  {city_id: 505, state_id: 4, name: "Староконстантинов", translit: "starokonstantinov"},
  {city_id: 507, state_id: 4, name: "Теофиполь", translit: "teofipol"},
  {city_id: 4, state_id: 4, name: "Хмельницкий", translit: "hmelnickiy"},
  {city_id: 510, state_id: 4, name: "Чемеровцы", translit: "chemerovciy"},
  {city_id: 511, state_id: 4, name: "Шепетовка", translit: "shepetovka"},
  {city_id: 512, state_id: 4, name: "Ярмолинцы", translit: "yarmolinciy"},
  {city_id: 645, state_id: 24, name: "Ватутино", translit: "Vatutino"},
  {city_id: 513, state_id: 24, name: "Городище", translit: "gorodishe"},
  {city_id: 514, state_id: 24, name: "Драбов", translit: "drabov"},
  {city_id: 515, state_id: 24, name: "Жашков", translit: "jashkov"},
  {city_id: 516, state_id: 24, name: "Звенигородка", translit: "zvenigorodka"},
  {city_id: 517, state_id: 24, name: "Золотоноша", translit: "zolotonosha"},
  {city_id: 518, state_id: 24, name: "Каменка", translit: "kamenka"},
  {city_id: 519, state_id: 24, name: "Канев", translit: "kanev"},
  {city_id: 520, state_id: 24, name: "Катеринополь", translit: "katerinopol"},
  {city_id: 521, state_id: 24, name: "Корсунь-Шевченковский", translit: "korsun-shevchenkovskiyi"},
  {city_id: 522, state_id: 24, name: "Лысянка", translit: "liysyanka"},
  {city_id: 523, state_id: 24, name: "Маньковка", translit: "mankovka"},
  {city_id: 524, state_id: 24, name: "Монастырище", translit: "monastiyrishe"},
  {city_id: 525, state_id: 24, name: "Смела", translit: "smela"},
  {city_id: 526, state_id: 24, name: "Тальное", translit: "talnoe"},
  {city_id: 527, state_id: 24, name: "Умань", translit: "uman"},
  {city_id: 528, state_id: 24, name: "Христиновка", translit: "hristinovka"},
  {city_id: 24, state_id: 24, name: "Черкассы", translit: "cherkassiy"},
  {city_id: 532, state_id: 24, name: "Чернобай", translit: "chernobayi"},
  {city_id: 531, state_id: 24, name: "Чигирин", translit: "chigirin"},
  {city_id: 533, state_id: 24, name: "Шпола", translit: "shpola"},
  {city_id: 546, state_id: 6, name: "Бахмач", translit: "bahmach"},
  {city_id: 547, state_id: 6, name: "Бобровица", translit: "bobrovica"},
  {city_id: 548, state_id: 6, name: "Борзна", translit: "borzna"},
  {city_id: 549, state_id: 6, name: "Варва", translit: "varva"},
  {city_id: 550, state_id: 6, name: "Городня", translit: "gorodnya"},
  {city_id: 551, state_id: 6, name: "Ичня", translit: "ichnya"},
  {city_id: 552, state_id: 6, name: "Козелец", translit: "kozelec"},
  {city_id: 553, state_id: 6, name: "Короп", translit: "korop"},
  {city_id: 554, state_id: 6, name: "Корюковка", translit: "koryukovka"},
  {city_id: 555, state_id: 6, name: "Куликовка", translit: "kulikovka"},
  {city_id: 556, state_id: 6, name: "Мена", translit: "mena"},
  {city_id: 557, state_id: 6, name: "Нежин", translit: "nejin"},
  {city_id: 558, state_id: 6, name: "Новгород-Северский", translit: "novgorod-severskiyi"},
  {city_id: 559, state_id: 6, name: "Носовка", translit: "nosovka"},
  {city_id: 560, state_id: 6, name: "Прилуки", translit: "priluki"},
  {city_id: 561, state_id: 6, name: "Репки", translit: "repki"},
  {city_id: 562, state_id: 6, name: "Семеновка", translit: "semenovka"},
  {city_id: 563, state_id: 6, name: "Сосница", translit: "sosnica"},
  {city_id: 564, state_id: 6, name: "Сребное", translit: "srebnoe"},
  {city_id: 565, state_id: 6, name: "Талалаевка", translit: "talalaevka"},
  {city_id: 6, state_id: 6, name: "Чернигов", translit: "chernigov"},
  {city_id: 568, state_id: 6, name: "Щорс", translit: "shors"},
  {city_id: 534, state_id: 25, name: "Вижница", translit: "vijnica"},
  {city_id: 535, state_id: 25, name: "Герца", translit: "gerca"},
  {city_id: 536, state_id: 25, name: "Глубокая", translit: "glubokaya"},
  {city_id: 537, state_id: 25, name: "Заставна", translit: "zastavna"},
  {city_id: 538, state_id: 25, name: "Кельменцы", translit: "kelmenciy"},
  {city_id: 539, state_id: 25, name: "Кицмань", translit: "kicman"},
  {city_id: 647, state_id: 25, name: "Новоднестровск", translit: "Novodnestrovsk"},
  {city_id: 540, state_id: 25, name: "Новоселица", translit: "novoselica"},
  {city_id: 541, state_id: 25, name: "Путила", translit: "putila"},
  {city_id: 542, state_id: 25, name: "Сокиряны", translit: "sokiryaniy"},
  {city_id: 543, state_id: 25, name: "Сторожинец", translit: "storojinec"},
  {city_id: 544, state_id: 25, name: "Хотин", translit: "hotin"},
  {city_id: 25, state_id: 25, name: "Черновцы", translit: "chernovciy"}
])
District.create!([
  {city_id: 10, area_id: 15186, name: "Святошинский", level: 1},
  {city_id: 10, area_id: 15185, name: "Соломенский", level: 1},
  {city_id: 10, area_id: 15949, name: "Троещина", level: 1},
  {city_id: 10, area_id: 15190, name: "Шевченковский", level: 1},
  {city_id: 10, area_id: 17420, name: "Борщаговка", level: 1},
  {city_id: 10, area_id: 15184, name: "Голосеевский", level: 1},
  {city_id: 10, area_id: 15181, name: "Дарницкий", level: 1},
  {city_id: 10, area_id: 15183, name: "Деснянский", level: 1},
  {city_id: 10, area_id: 15182, name: "Днепровский", level: 1},
  {city_id: 10, area_id: 15187, name: "Оболонский", level: 1},
  {city_id: 10, area_id: 15189, name: "Печерский", level: 1},
  {city_id: 10, area_id: 15188, name: "Подольский", level: 1}
])

District.create!([
		                 {city_id: 10, area_id: 101, name: "Академгородок", level: 4, parent_area_id: 15186},
		                 {city_id: 10, area_id: 102, name: "Беличи", level: 4, parent_area_id: 15186},
		                 {city_id: 10, area_id: 103, name: "Березняки", level: 4, parent_area_id: 15182},
		                 {city_id: 10, area_id: 104, name: "Бортничи", level: 4, parent_area_id: 15181},
		                 {city_id: 10, area_id: 105, name: "Борщаговка", level: 4, parent_area_id: 15186},
		                 {city_id: 10, area_id: 106, name: "Ветряные Горы", level: 4, parent_area_id: 15188},
		                 {city_id: 10, area_id: 107, name: "Виноградарь", level: 4, parent_area_id: 15188},
		                 {city_id: 10, area_id: 108, name: "Воскресенка", level: 4, parent_area_id: 15182},
		                 {city_id: 10, area_id: 109, name: "Галаганы", level: 4, parent_area_id: 15186},
		                 {city_id: 10, area_id: 110, name: "Голосеево", level: 4, parent_area_id: 15184},
		                 {city_id: 10, area_id: 111, name: "ДВРЗ", level: 4, parent_area_id: 15182},
		                 {city_id: 10, area_id: 112, name: "Комсомольский", level: 4, parent_area_id: 15182},
		                 {city_id: 10, area_id: 113, name: "Кудрявец", level: 4, parent_area_id: 15190},
		                 {city_id: 10, area_id: 114, name: "Куреневка", level: 4, parent_area_id: 15187},
		                 {city_id: 10, area_id: 115, name: "Левобережный массив", level: 4, parent_area_id: 15182},
		                 {city_id: 10, area_id: 116, name: "Лесной", level: 4, parent_area_id: 15183},
		                 {city_id: 10, area_id: 117, name: "Липки", level: 4, parent_area_id: 15189},
		                 {city_id: 10, area_id: 118, name: "Лукьяновка", level: 4, parent_area_id: 15190},
		                 {city_id: 10, area_id: 119, name: "Минский", level: 4, parent_area_id: 15187},
		                 {city_id: 10, area_id: 120, name: "Мостицкий массив", level: 4, parent_area_id: 15188},
		                 {city_id: 10, area_id: 121, name: "Нивки", level: 4, parent_area_id: 15190},
		                 {city_id: 10, area_id: 122, name: "Новое строение", level: 4, parent_area_id: 15190},
		                 {city_id: 10, area_id: 123, name: "Оболонь", level: 4, parent_area_id: 15187},
		                 {city_id: 10, area_id: 124, name: "Осокорки", level: 4, parent_area_id: 15181},
		                 {city_id: 10, area_id: 125, name: "Отрадный", level: 4, parent_area_id: 15185},
		                 {city_id: 10, area_id: 126, name: "Печерск", level: 4, parent_area_id: 15189},
		                 {city_id: 10, area_id: 127, name: "Подол", level: 4, parent_area_id: 15188},
		                 {city_id: 10, area_id: 128, name: "Позняки", level: 4, parent_area_id: 15181},
		                 {city_id: 10, area_id: 129, name: "Пуща-Водица", level: 4, parent_area_id: 15187},
		                 {city_id: 10, area_id: 130, name: "Русановка", level: 4, parent_area_id: 15182},
		                 {city_id: 10, area_id: 131, name: "Саперная Слободка", level: 4, parent_area_id: 15184},
		                 {city_id: 10, area_id: 132, name: "Святошино", level: 4, parent_area_id: 15186},
		                 {city_id: 10, area_id: 133, name: "Соломенка", level: 4, parent_area_id: 15185},
		                 {city_id: 10, area_id: 134, name: "Соцгород", level: 4, parent_area_id: 15182},
		                 {city_id: 10, area_id: 135, name: "Старый Киев", level: 4, parent_area_id: 15190},
		                 {city_id: 10, area_id: 136, name: "Сырец", level: 4, parent_area_id: 15190},
		                 {city_id: 10, area_id: 137, name: "Татарка", level: 4, parent_area_id: 15190},
		                 {city_id: 10, area_id: 138, name: "Теремки", level: 4, parent_area_id: 15184},
		                 {city_id: 10, area_id: 139, name: "Троещина", level: 4, parent_area_id: 15183},
		                 {city_id: 10, area_id: 140, name: "Харьковский", level: 4, parent_area_id: 15181},
		                 {city_id: 10, area_id: 141, name: "Чёрная гора", level: 4, parent_area_id: 15189},
		                 {city_id: 10, area_id: 142, name: "Шулявка", level: 4, parent_area_id: 15190}
                 ])