=begin
User.create!(lastName: 'Admin', firstName: 'Admin', email: 'admin@example.com', password: 'estateadminpass', password_confirmation: 'estateadminpass')

Region.create!([
  {region_id: 1, name: "Винницкая", translit: "vynnytskaia"},
  {region_id: 18, name: "Волынская", translit: "volynskaia"},
  {region_id: 11, name: "Днепропетровская", translit: "dnepropetrovskaia"},
  {region_id: 13, name: "Донецкая", translit: "donetskaia"},
  {region_id: 2, name: "Житомирская", translit: "zhytomyrskaia"},
  {region_id: 22, name: "Закарпатская", translit: "zakarpatskaia"},
  {region_id: 14, name: "Запорожская", translit: "zaporozhskaia"},
  {region_id: 15, name: "Ивано-Франковская", translit: "yvano-frankovskaia"},
  {region_id: 10, name: "Киевская", translit: "kyevskaia"},
  {region_id: 16, name: "Кировоградская", translit: "kyrovogradskaia"},
  {region_id: 17, name: "Луганская", translit: "luganskaia"},
  {region_id: 5, name: "Львовская", translit: "lvovskaia"},
  {region_id: 19, name: "Николаевская", translit: "nykolaevskaia"},
  {region_id: 12, name: "Одесская", translit: "odesskaia"},
  {region_id: 20, name: "Полтавская", translit: "poltavskaia"},
  {region_id: 21, name: "Республика Крым", translit: "respublyka krym"},
  {region_id: 9, name: "Ровенская", translit: "rovenskaia"},
  {region_id: 8, name: "Сумская", translit: "sumskaia"},
  {region_id: 3, name: "Тернопольская", translit: "ternopolskaia"},
  {region_id: 7, name: "Харьковская", translit: "kharkovskaia"},
  {region_id: 23, name: "Херсонская", translit: "khersonskaia"},
  {region_id: 4, name: "Хмельницкая", translit: "khmelnytskaia"},
  {region_id: 24, name: "Черкасская", translit: "cherkasskaia"},
  {region_id: 6, name: "Черниговская", translit: "chernygovskaia"},
  {region_id: 25, name: "Черновицкая", translit: "chernovytskaia"}
])
=end
City.create!([
  {city_id: 597, region_id: 1, name: "Бар", translit: "bar"},
  {city_id: 599, region_id: 1, name: "Бершадь", translit: "bershad"},
  {city_id: 1, region_id: 1, name: "Винница", translit: "vinnica"},
  {city_id: 602, region_id: 1, name: "Гайсин", translit: "gayisin"},
  {city_id: 609, region_id: 1, name: "Гнивань", translit: "gnivan"},
  {city_id: 27, region_id: 1, name: "Жмеринка", translit: "jmerinka"},
  {city_id: 603, region_id: 1, name: "Ильинцы", translit: "ilinciy"},
  {city_id: 30, region_id: 1, name: "Казатин", translit: "kazatin"},
  {city_id: 604, region_id: 1, name: "Калиновка", translit: "kalinovka"},
  {city_id: 31, region_id: 1, name: "Крыжополь", translit: "kriyjopol"},
  {city_id: 644, region_id: 1, name: "Ладыжин", translit: "Ladujun"},
  {city_id: 32, region_id: 1, name: "Липовец", translit: "lipovec"},
  {city_id: 33, region_id: 1, name: "Литин", translit: "litin"},
  {city_id: 34, region_id: 1, name: "Могилев-Подольский", translit: "mogilev-podolskiyi"},
  {city_id: 35, region_id: 1, name: "Мурованые Куриловцы", translit: "murovaniye_kurilovciy"},
  {city_id: 36, region_id: 1, name: "Немиров", translit: "nemirov"},
  {city_id: 37, region_id: 1, name: "Оратов", translit: "jratov"},
  {city_id: 38, region_id: 1, name: "Песчанка", translit: "peschanka"},
  {city_id: 39, region_id: 1, name: "Погребище", translit: "pogrebishe"},
  {city_id: 40, region_id: 1, name: "Теплик", translit: "teplik"},
  {city_id: 42, region_id: 1, name: "Томашполь", translit: "tomashpol"},
  {city_id: 43, region_id: 1, name: "Тростянец", translit: "trostyanec"},
  {city_id: 44, region_id: 1, name: "Тульчин", translit: "tulchin"},
  {city_id: 41, region_id: 1, name: "Тывров", translit: "tiyvrov"},
  {city_id: 45, region_id: 1, name: "Хмельник", translit: "hmelnik"},
  {city_id: 46, region_id: 1, name: "Черновцы", translit: "chernovciy"},
  {city_id: 47, region_id: 1, name: "Чечельник", translit: "chechelnik"},
  {city_id: 48, region_id: 1, name: "Шаргород", translit: "shargorod"},
  {city_id: 49, region_id: 1, name: "Ямполь", translit: "yampol"},
  {city_id: 50, region_id: 18, name: "Владимир-Волынский", translit: "vladimir-voliynskiyi"},
  {city_id: 51, region_id: 18, name: "Горохов", translit: "gorohov"},
  {city_id: 52, region_id: 18, name: "Иваничи", translit: "ivanichi"},
  {city_id: 53, region_id: 18, name: "Камень-Каширский", translit: "kamen-kashirskiyi"},
  {city_id: 54, region_id: 18, name: "Киверцы", translit: "kiverciy"},
  {city_id: 55, region_id: 18, name: "Ковель", translit: "kovel"},
  {city_id: 56, region_id: 18, name: "Локачи", translit: "lokachi"},
  {city_id: 18, region_id: 18, name: "Луцк", translit: "luck"},
  {city_id: 59, region_id: 18, name: "Любешов", translit: "lyubeshov"},
  {city_id: 60, region_id: 18, name: "Любомль", translit: "lyuboml"},
  {city_id: 61, region_id: 18, name: "Маневичи", translit: "manevichi"},
  {city_id: 62, region_id: 18, name: "Нововолынск", translit: "novovoliynsk"},
  {city_id: 63, region_id: 18, name: "Ратно", translit: "ratno"},
  {city_id: 64, region_id: 18, name: "Рожище", translit: "rojishe"},
  {city_id: 65, region_id: 18, name: "Старая Выжевка", translit: "staraya_viyjevka"},
  {city_id: 66, region_id: 18, name: "Турийск", translit: "turiyisk"},
  {city_id: 67, region_id: 18, name: "Шацк", translit: "shack"},
  {city_id: 68, region_id: 11, name: "Апостоловo", translit: "apostolovo"},
  {city_id: 69, region_id: 11, name: "Васильковка", translit: "vasilkovka"},
  {city_id: 70, region_id: 11, name: "Верхнеднепровск", translit: "verhnedneprovsk"},
  {city_id: 71, region_id: 11, name: "Вольногорск", translit: "volnogorsk"},
  {city_id: 72, region_id: 11, name: "Днепродзержинск", translit: "dneprodzerjinsk"},
  {city_id: 11, region_id: 11, name: "Днепропетровск", translit: "dnepropetrovsk"},
  {city_id: 75, region_id: 11, name: "Желтые Воды", translit: "jeltiye_vodiy"},
  {city_id: 76, region_id: 11, name: "Кривой Рог", translit: "krivoyi_rog"},
  {city_id: 78, region_id: 11, name: "Кринички", translit: "krinichki"},
  {city_id: 79, region_id: 11, name: "Магдалиновка", translit: "magdalinovka"},
  {city_id: 80, region_id: 11, name: "Марганец", translit: "marganec"},
  {city_id: 81, region_id: 11, name: "Межевая", translit: "mejevaya"},
  {city_id: 82, region_id: 11, name: "Никополь", translit: "nikopol"},
  {city_id: 83, region_id: 11, name: "Новомосковск", translit: "novomoskovsk"},
  {city_id: 84, region_id: 11, name: "Орджоникидзе", translit: "jrdjonikidze"},
  {city_id: 85, region_id: 11, name: "Павлоград", translit: "pavlograd"},
  {city_id: 86, region_id: 11, name: "Першотравенск", translit: "pershotravensk"},
  {city_id: 87, region_id: 11, name: "Петриковка", translit: "petrikovka"},
  {city_id: 88, region_id: 11, name: "Петропавловка", translit: "petropavlovka"},
  {city_id: 89, region_id: 11, name: "Покровское", translit: "pokrovskoe"},
  {city_id: 90, region_id: 11, name: "Пятихатки", translit: "pyatihatki"},
  {city_id: 91, region_id: 11, name: "Синельниково", translit: "sinelnikovo"},
  {city_id: 92, region_id: 11, name: "Соленое", translit: "solenoe"},
  {city_id: 93, region_id: 11, name: "Софиевка", translit: "sofievka"},
  {city_id: 94, region_id: 11, name: "Терновка", translit: "ternovka"},
  {city_id: 95, region_id: 11, name: "Томаковка", translit: "tomakovka"},
  {city_id: 96, region_id: 11, name: "Царичанка", translit: "carichanka"},
  {city_id: 97, region_id: 11, name: "Широкое", translit: "shirokoe"},
  {city_id: 98, region_id: 11, name: "Юрьевка", translit: "yurevka"},
  {city_id: 607, region_id: 13, name: "Авдеевка", translit: "avdeevka"},
  {city_id: 121, region_id: 13, name: "Александровка", translit: "aleksandrovka"},
  {city_id: 99, region_id: 13, name: "Амвросиевка", translit: "amvrosievka"},
  {city_id: 100, region_id: 13, name: "Артемовск", translit: "artemovsk"},
  {city_id: 101, region_id: 13, name: "Великая Новоселка", translit: "velikaya_novoselka"},
  {city_id: 102, region_id: 13, name: "Волноваха", translit: "volnovaha"},
  {city_id: 103, region_id: 13, name: "Володарское", translit: "volodarskoe"},
  {city_id: 104, region_id: 13, name: "Горловка", translit: "gorlovka"},
  {city_id: 105, region_id: 13, name: "Дебальцево", translit: "debalcevo"},
  {city_id: 106, region_id: 13, name: "Дзержинск", translit: "dzerjinsk"},
  {city_id: 638, region_id: 13, name: "Димитров", translit: "Dimitrov"},
  {city_id: 107, region_id: 13, name: "Доброполье", translit: "dobropole"},
  {city_id: 639, region_id: 13, name: "Докучаевск", translit: "Dokuchaevsk"},
  {city_id: 13, region_id: 13, name: "Донецк", translit: "doneck"},
  {city_id: 109, region_id: 13, name: "Дружковка", translit: "drujkovka"},
  {city_id: 110, region_id: 13, name: "Енакиево", translit: "enakievo"},
  {city_id: 640, region_id: 13, name: "Ждановка", translit: "Jdanovka"},
  {city_id: 111, region_id: 13, name: "Кировское", translit: "kirovskoe"},
  {city_id: 112, region_id: 13, name: "Константиновка", translit: "konstantinovka"},
  {city_id: 113, region_id: 13, name: "Краматорск", translit: "kramatorsk"},
  {city_id: 114, region_id: 13, name: "Красноармейск", translit: "krasnoarmeyisk"},
  {city_id: 115, region_id: 13, name: "Красный Лиман", translit: "krasniyyi_liman"},
  {city_id: 116, region_id: 13, name: "Макеевка", translit: "makeevka"},
  {city_id: 117, region_id: 13, name: "Мангуш", translit: "mangush"},
  {city_id: 119, region_id: 13, name: "Мариуполь", translit: "mariupol"},
  {city_id: 118, region_id: 13, name: "Марьинка", translit: "marinka"},
  {city_id: 120, region_id: 13, name: "Новоазовск", translit: "novoazovsk"},
  {city_id: 641, region_id: 13, name: "Новогродовка", translit: "Novogrodovka"},
  {city_id: 122, region_id: 13, name: "Селидово", translit: "selidovo"},
  {city_id: 123, region_id: 13, name: "Славянск", translit: "slavyansk"},
  {city_id: 124, region_id: 13, name: "Снежное", translit: "snejnoe"},
  {city_id: 125, region_id: 13, name: "Старобешево", translit: "starobeshevo"},
  {city_id: 126, region_id: 13, name: "Тельманово", translit: "telmanovo"},
  {city_id: 127, region_id: 13, name: "Торез", translit: "torez"},
  {city_id: 642, region_id: 13, name: "Угледар", translit: "Ugledar"},
  {city_id: 128, region_id: 13, name: "Харцызск", translit: "harciyzsk"},
  {city_id: 129, region_id: 13, name: "Шахтарск", translit: "shahtarsk"},
  {city_id: 130, region_id: 13, name: "Ясиноватая", translit: "yasinovataya"},
  {city_id: 131, region_id: 2, name: "Андрушевка", translit: "andrushevka"},
  {city_id: 132, region_id: 2, name: "Барановка", translit: "baranovka"},
  {city_id: 133, region_id: 2, name: "Бердичев", translit: "berdichev"},
  {city_id: 134, region_id: 2, name: "Брусилов", translit: "brusilov"},
  {city_id: 135, region_id: 2, name: "Володарск-Волынский", translit: "volodarsk-voliynskiyi"},
  {city_id: 137, region_id: 2, name: "Емильчино", translit: "emilchino"},
  {city_id: 2, region_id: 2, name: "Житомир", translit: "jitomir"},
  {city_id: 140, region_id: 2, name: "Коростень", translit: "korosten"},
  {city_id: 141, region_id: 2, name: "Коростышев", translit: "korostiyshev"},
  {city_id: 142, region_id: 2, name: "Лугины", translit: "luginiy"},
  {city_id: 143, region_id: 2, name: "Любар", translit: "lyubar"},
  {city_id: 144, region_id: 2, name: "Малин", translit: "malin"},
  {city_id: 145, region_id: 2, name: "Народичи", translit: "narodichi"},
  {city_id: 146, region_id: 2, name: "Новоград-Волынский", translit: "novograd-voliynskiyi"},
  {city_id: 147, region_id: 2, name: "Овруч", translit: "jvruch"},
  {city_id: 148, region_id: 2, name: "Олевск", translit: "jlevsk"},
  {city_id: 149, region_id: 2, name: "Попельня", translit: "popelnya"},
  {city_id: 150, region_id: 2, name: "Радомышль", translit: "radomiyshl"},
  {city_id: 606, region_id: 2, name: "Романов", translit: "romanov"},
  {city_id: 151, region_id: 2, name: "Ружин", translit: "rujin"},
  {city_id: 152, region_id: 2, name: "Червоноармейск", translit: "chervonoarmeyisk"},
  {city_id: 153, region_id: 2, name: "Черняхов", translit: "chernyahov"},
  {city_id: 154, region_id: 2, name: "Чуднов", translit: "chudnov"},
  {city_id: 155, region_id: 22, name: "Берегово", translit: "beregovo"},
  {city_id: 156, region_id: 22, name: "Великий Березный", translit: "velikiyi_berezniyyi"},
  {city_id: 157, region_id: 22, name: "Виноградов", translit: "vinogradov"},
  {city_id: 158, region_id: 22, name: "Воловец", translit: "volovec"},
  {city_id: 619, region_id: 22, name: "Драгобрат", translit: "Dragobrat"},
  {city_id: 159, region_id: 22, name: "Иршавa", translit: "irshava"},
  {city_id: 160, region_id: 22, name: "Межгорье", translit: "mejgore"},
  {city_id: 161, region_id: 22, name: "Мукачево", translit: "mukachevo"},
  {city_id: 162, region_id: 22, name: "Перечин", translit: "perechin"},
  {city_id: 163, region_id: 22, name: "Рахов", translit: "rahov"},
  {city_id: 164, region_id: 22, name: "Свалява", translit: "svalyava"},
  {city_id: 165, region_id: 22, name: "Тячев", translit: "tyachev"},
  {city_id: 22, region_id: 22, name: "Ужгород", translit: "ujgorod"},
  {city_id: 168, region_id: 22, name: "Хуст", translit: "hust"},
  {city_id: 169, region_id: 22, name: "Чоп", translit: "chop"},
  {city_id: 191, region_id: 14, name: "Акимовка", translit: "akimovka"},
  {city_id: 170, region_id: 14, name: "Бердянск", translit: "berdyansk"},
  {city_id: 171, region_id: 14, name: "Васильевка", translit: "vasilevka"},
  {city_id: 172, region_id: 14, name: "Великая Белозерка", translit: "velikaya_belozerka"},
  {city_id: 173, region_id: 14, name: "Веселоe", translit: "veseloe"},
  {city_id: 174, region_id: 14, name: "Вольнянск", translit: "volnyansk"},
  {city_id: 175, region_id: 14, name: "Гуляйполe", translit: "gulyayipole"},
  {city_id: 14, region_id: 14, name: "Запорожье", translit: "zaporoje"},
  {city_id: 179, region_id: 14, name: "Каменка-Днепровская", translit: "kamenka-dneprovskaya"},
  {city_id: 180, region_id: 14, name: "Куйбышево", translit: "kuyibiyshevo"},
  {city_id: 28, region_id: 14, name: "Мелитополь", translit: "melitopol"},
  {city_id: 182, region_id: 14, name: "Михайловка", translit: "mihayilovka"},
  {city_id: 183, region_id: 14, name: "Новониколаевка", translit: "novonikolaevka"},
  {city_id: 184, region_id: 14, name: "Орехов", translit: "jrehov"},
  {city_id: 185, region_id: 14, name: "Пологи", translit: "pologi"},
  {city_id: 186, region_id: 14, name: "Приазовское", translit: "priazovskoe"},
  {city_id: 187, region_id: 14, name: "Приморск", translit: "primorsk"},
  {city_id: 188, region_id: 14, name: "Розовка", translit: "rozovka"},
  {city_id: 189, region_id: 14, name: "Токмак", translit: "tokmak"},
  {city_id: 190, region_id: 14, name: "Черниговка", translit: "chernigovka"},
  {city_id: 176, region_id: 14, name: "Энергодар", translit: "yenergodar"},
  {city_id: 192, region_id: 15, name: "Богородчаны", translit: "bogorodchaniy"},
  {city_id: 193, region_id: 15, name: "Болехов", translit: "bolehov"},
  {city_id: 621, region_id: 15, name: "Буковель", translit: "Bukovel"},
  {city_id: 608, region_id: 15, name: "Бурштын", translit: "burshtyn"},
  {city_id: 194, region_id: 15, name: "Верховина", translit: "verhovina"},
  {city_id: 195, region_id: 15, name: "Галич", translit: "galich"},
  {city_id: 196, region_id: 15, name: "Городенка", translit: "gorodenka"},
  {city_id: 197, region_id: 15, name: "Долина", translit: "dolina"},
  {city_id: 15, region_id: 15, name: "Ивано-Франковск", translit: "ivano-frankovsk"},
  {city_id: 199, region_id: 15, name: "Калуш", translit: "kalush"},
  {city_id: 200, region_id: 15, name: "Коломыя", translit: "kolomiyya"},
  {city_id: 201, region_id: 15, name: "Косов", translit: "kosov"},
  {city_id: 202, region_id: 15, name: "Надворная", translit: "nadvornaya"},
  {city_id: 203, region_id: 15, name: "Рогатин", translit: "rogatin"},
  {city_id: 204, region_id: 15, name: "Рожнятов", translit: "rojnyatov"},
  {city_id: 205, region_id: 15, name: "Снятин", translit: "snyatin"},
  {city_id: 207, region_id: 15, name: "Тлумач", translit: "tlumach"},
  {city_id: 206, region_id: 15, name: "Тысменица", translit: "tiysmenica"},
  {city_id: 208, region_id: 15, name: "Яремча", translit: "yaremcha"},
  {city_id: 209, region_id: 10, name: "Барышевка", translit: "bariyshevka"},
  {city_id: 210, region_id: 10, name: "Белая Церковь", translit: "belaya_cerkov"},
  {city_id: 636, region_id: 10, name: "Березань", translit: "berezan"},
  {city_id: 211, region_id: 10, name: "Богуслав", translit: "boguslav"},
  {city_id: 212, region_id: 10, name: "Борисполь", translit: "borispol"},
  {city_id: 213, region_id: 10, name: "Бородянка", translit: "borodyanka"},
  {city_id: 214, region_id: 10, name: "Бровары", translit: "brovariy"},
  {city_id: 612, region_id: 10, name: "Буча", translit: "bucha"},
  {city_id: 215, region_id: 10, name: "Васильков", translit: "vasilkov"},
  {city_id: 217, region_id: 10, name: "Володарка", translit: "volodarka"},
  {city_id: 216, region_id: 10, name: "Вышгород", translit: "viyshgorod"},
  {city_id: 218, region_id: 10, name: "Згуровка", translit: "zgurovka"},
  {city_id: 219, region_id: 10, name: "Иванков", translit: "ivankov"},
  {city_id: 220, region_id: 10, name: "Ирпень", translit: "irpen"},
  {city_id: 221, region_id: 10, name: "Кагарлык", translit: "kagarliyk"},
  {city_id: 10, region_id: 10, name: "Киев", translit: "kiev"},
  {city_id: 648, region_id: 10, name: "Киево-Святошинский", translit: "Kievo-Svyatoshinskiy"},
  {city_id: 223, region_id: 10, name: "Макаров", translit: "makarov"},
  {city_id: 224, region_id: 10, name: "Мироновка", translit: "mironovka"},
  {city_id: 225, region_id: 10, name: "Обухов", translit: "jbuhov"},
  {city_id: 226, region_id: 10, name: "Переяслав-Хмельницкий", translit: "pereyaslav-hmelnickiyi"},
  {city_id: 227, region_id: 10, name: "Полесское", translit: "polesskoe"},
  {city_id: 228, region_id: 10, name: "Ракитное", translit: "rokitnoe"},
  {city_id: 626, region_id: 10, name: "Ржищев", translit: "rzishev"},
  {city_id: 229, region_id: 10, name: "Сквирa", translit: "skvira"},
  {city_id: 230, region_id: 10, name: "Славутич", translit: "slavutich"},
  {city_id: 231, region_id: 10, name: "Ставище", translit: "stavishe"},
  {city_id: 232, region_id: 10, name: "Тараща", translit: "tarasha"},
  {city_id: 233, region_id: 10, name: "Тетиев", translit: "tetiev"},
  {city_id: 234, region_id: 10, name: "Фастов", translit: "fastov"},
  {city_id: 235, region_id: 10, name: "Яготин", translit: "yagotin"},
  {city_id: 252, region_id: 16, name: "Александрия", translit: "aleksandriya"},
  {city_id: 251, region_id: 16, name: "Александровка", translit: "aleksandrovka"},
  {city_id: 236, region_id: 16, name: "Бобринец", translit: "bobrinec"},
  {city_id: 238, region_id: 16, name: "Гайворон", translit: "gayivoron"},
  {city_id: 239, region_id: 16, name: "Голованевск", translit: "golovanevsk"},
  {city_id: 240, region_id: 16, name: "Добровеличковка", translit: "dobrovelichkovka"},
  {city_id: 241, region_id: 16, name: "Долинская", translit: "dolinskaya"},
  {city_id: 242, region_id: 16, name: "Знаменка", translit: "znamenka"},
  {city_id: 16, region_id: 16, name: "Кировоград", translit: "kirovograd"},
  {city_id: 245, region_id: 16, name: "Компанеевка", translit: "kompaneevka"},
  {city_id: 246, region_id: 16, name: "Малая Виска", translit: "malaya_viska"},
  {city_id: 247, region_id: 16, name: "Новгородкa", translit: "novgorodka"},
  {city_id: 248, region_id: 16, name: "Новоархангельск", translit: "novoarhangelsk"},
  {city_id: 249, region_id: 16, name: "Новомиргород", translit: "novomirgorod"},
  {city_id: 250, region_id: 16, name: "Новоукраинка", translit: "novoukrainka"},
  {city_id: 237, region_id: 16, name: "Ольшанка", translit: "olshanka"},
  {city_id: 253, region_id: 16, name: "Онуфриевка", translit: "jnufrievka"},
  {city_id: 254, region_id: 16, name: "Петрово", translit: "petrovo"},
  {city_id: 255, region_id: 16, name: "Светловодск", translit: "svetlovodsk"},
  {city_id: 256, region_id: 16, name: "Ульяновка", translit: "ulyanovka"},
  {city_id: 257, region_id: 16, name: "Устиновка", translit: "ustinovka"},
  {city_id: 258, region_id: 17, name: "Алчевск", translit: "alchevsk"},
  {city_id: 259, region_id: 17, name: "Антрацит", translit: "antracit"},
  {city_id: 260, region_id: 17, name: "Беловодск", translit: "belovodsk"},
  {city_id: 261, region_id: 17, name: "Белокуракинo", translit: "belokurakino"},
  {city_id: 262, region_id: 17, name: "Брянка", translit: "bryanka"},
  {city_id: 263, region_id: 17, name: "Кировск", translit: "kirovsk"},
  {city_id: 264, region_id: 17, name: "Краснодон", translit: "krasnodon"},
  {city_id: 265, region_id: 17, name: "Красный Луч", translit: "krasniyyi_luch"},
  {city_id: 266, region_id: 17, name: "Кременная", translit: "kremennaya"},
  {city_id: 267, region_id: 17, name: "Лисичанск", translit: "lisichansk"},
  {city_id: 17, region_id: 17, name: "Луганск", translit: "lugansk"},
  {city_id: 269, region_id: 17, name: "Лутугино", translit: "lutugino"},
  {city_id: 270, region_id: 17, name: "Марковка", translit: "markovka"},
  {city_id: 271, region_id: 17, name: "Меловое", translit: "melovoe"},
  {city_id: 272, region_id: 17, name: "Новоайдар", translit: "novoayidar"},
  {city_id: 273, region_id: 17, name: "Новопсков", translit: "novopskov"},
  {city_id: 274, region_id: 17, name: "Первомайск", translit: "pervomayisk"},
  {city_id: 275, region_id: 17, name: "Перевальск", translit: "perevalsk"},
  {city_id: 276, region_id: 17, name: "Попасная", translit: "popasnaya"},
  {city_id: 277, region_id: 17, name: "Ровеньки", translit: "rovenki"},
  {city_id: 278, region_id: 17, name: "Рубежное", translit: "rubejnoe"},
  {city_id: 279, region_id: 17, name: "Сватовo", translit: "svatovo"},
  {city_id: 280, region_id: 17, name: "Свердловск", translit: "sverdlovsk"},
  {city_id: 281, region_id: 17, name: "Северодонецк", translit: "severodoneck"},
  {city_id: 282, region_id: 17, name: "Славяносербск", translit: "slavyanoserbsk"},
  {city_id: 283, region_id: 17, name: "Станично-Луганское", translit: "stanichno-luganskoe"},
  {city_id: 284, region_id: 17, name: "Старобельск", translit: "starobelsk"},
  {city_id: 285, region_id: 17, name: "Стаханов", translit: "stahanov"},
  {city_id: 286, region_id: 17, name: "Троицкое", translit: "troickoe"},
  {city_id: 287, region_id: 5, name: "Борислав", translit: "borislav"},
  {city_id: 288, region_id: 5, name: "Броды", translit: "brodiy"},
  {city_id: 289, region_id: 5, name: "Буск", translit: "busk"},
  {city_id: 290, region_id: 5, name: "Городок", translit: "gorodok"},
  {city_id: 291, region_id: 5, name: "Дрогобыч", translit: "drogobiych"},
  {city_id: 292, region_id: 5, name: "Жидачов", translit: "jidachov"},
  {city_id: 293, region_id: 5, name: "Жолква", translit: "jovkva"},
  {city_id: 294, region_id: 5, name: "Золочев", translit: "zolochev"},
  {city_id: 295, region_id: 5, name: "Каменка-Бугская", translit: "kamenka-bugskaya"},
  {city_id: 5, region_id: 5, name: "Львов", translit: "lvov"},
  {city_id: 646, region_id: 5, name: "Моршин", translit: "Morshun"},
  {city_id: 298, region_id: 5, name: "Мостиска", translit: "mostiska"},
  {city_id: 297, region_id: 5, name: "Николаев", translit: "nikolaev"},
  {city_id: 632, region_id: 5, name: "Новий Роздол", translit: "noviy-rozdil"},
  {city_id: 299, region_id: 5, name: "Перемышляны", translit: "peremiyshlyaniy"},
  {city_id: 300, region_id: 5, name: "Пустомыты", translit: "pustomiytiy"},
  {city_id: 301, region_id: 5, name: "Радехов", translit: "radehov"},
  {city_id: 302, region_id: 5, name: "Самбор", translit: "sambor"},
  {city_id: 303, region_id: 5, name: "Сколе", translit: "skole"},
  {city_id: 304, region_id: 5, name: "Сокаль", translit: "sokal"},
  {city_id: 614, region_id: 5, name: "Сосновка", translit: "sosnovka"},
  {city_id: 305, region_id: 5, name: "Старый Самбор", translit: "stariyyi_sambor"},
  {city_id: 306, region_id: 5, name: "Стрый", translit: "striyyi"},
  {city_id: 307, region_id: 5, name: "Трускавец", translit: "truskavec"},
  {city_id: 308, region_id: 5, name: "Турка", translit: "turka"},
  {city_id: 309, region_id: 5, name: "Червоноград", translit: "chervonograd"},
  {city_id: 310, region_id: 5, name: "Яворов", translit: "yavorov"},
  {city_id: 311, region_id: 19, name: "Арбузинка", translit: "arbuzinka"},
  {city_id: 312, region_id: 19, name: "Баштанка", translit: "bashtanka"},
  {city_id: 313, region_id: 19, name: "Березанка", translit: "berezanka"},
  {city_id: 314, region_id: 19, name: "Березнеговатое", translit: "bereznegovatoe"},
  {city_id: 315, region_id: 19, name: "Братское", translit: "bratskoe"},
  {city_id: 316, region_id: 19, name: "Веселиново", translit: "veselinovo"},
  {city_id: 317, region_id: 19, name: "Вознесенск", translit: "voznesensk"},
  {city_id: 318, region_id: 19, name: "Врадиевка", translit: "vradievka"},
  {city_id: 319, region_id: 19, name: "Доманевка", translit: "domanevka"},
  {city_id: 320, region_id: 19, name: "Еланец", translit: "elanec"},
  {city_id: 321, region_id: 19, name: "Жовтневый район", translit: "jovtneviyyi_rayion"},
  {city_id: 322, region_id: 19, name: "Казанка", translit: "kazanka"},
  {city_id: 613, region_id: 19, name: "Коблево", translit: "Koblevo"},
  {city_id: 323, region_id: 19, name: "Кривое Озеро", translit: "krivoe_jzero"},
  {city_id: 19, region_id: 19, name: "Николаев", translit: "nikolaev"},
  {city_id: 327, region_id: 19, name: "Новая Одесса", translit: "novaya_jdessa"},
  {city_id: 326, region_id: 19, name: "Новый Буг", translit: "noviyyi_bug"},
  {city_id: 328, region_id: 19, name: "Очаков", translit: "jchakov"},
  {city_id: 329, region_id: 19, name: "Первомайск", translit: "pervomayisk"},
  {city_id: 330, region_id: 19, name: "Снигиревка", translit: "snigirevka"},
  {city_id: 331, region_id: 19, name: "Южноукраинск", translit: "yujnoukrainsk"},
  {city_id: 332, region_id: 12, name: "Ананьев", translit: "ananev"},
  {city_id: 333, region_id: 12, name: "Арциз", translit: "arciz"},
  {city_id: 334, region_id: 12, name: "Балта", translit: "balta"},
  {city_id: 336, region_id: 12, name: "Белгород-Днестровский", translit: "belgorod-dnestrovskiyi"},
  {city_id: 337, region_id: 12, name: "Беляевка", translit: "belyaevka"},
  {city_id: 335, region_id: 12, name: "Березовка", translit: "berezovka"},
  {city_id: 338, region_id: 12, name: "Болград", translit: "bolgrad"},
  {city_id: 339, region_id: 12, name: "Великая Михайловка", translit: "velikaya_mihayilovka"},
  {city_id: 625, region_id: 12, name: "Затока", translit: "Zatoka"},
  {city_id: 340, region_id: 12, name: "Ивановка", translit: "ivanovka"},
  {city_id: 341, region_id: 12, name: "Измаил", translit: "izmail"},
  {city_id: 342, region_id: 12, name: "Ильичевск", translit: "ilichevsk"},
  {city_id: 343, region_id: 12, name: "Килия", translit: "kiliya"},
  {city_id: 344, region_id: 12, name: "Кодыма", translit: "kodiyma"},
  {city_id: 345, region_id: 12, name: "Коминтерновское", translit: "kominternovskoe"},
  {city_id: 346, region_id: 12, name: "Котовск", translit: "kotovsk"},
  {city_id: 347, region_id: 12, name: "Красные Окны", translit: "krasniye_jkniy"},
  {city_id: 348, region_id: 12, name: "Любашевка", translit: "lyubashevka"},
  {city_id: 349, region_id: 12, name: "Николаевка", translit: "nikolaevka"},
  {city_id: 350, region_id: 12, name: "Овидиополь", translit: "jvidiopol"},
  {city_id: 12, region_id: 12, name: "Одесса", translit: "odessa"},
  {city_id: 353, region_id: 12, name: "Раздельная", translit: "razdelnaya"},
  {city_id: 352, region_id: 12, name: "Рени", translit: "reni"},
  {city_id: 354, region_id: 12, name: "Саврань", translit: "savran"},
  {city_id: 355, region_id: 12, name: "Сарата", translit: "sarata"},
  {city_id: 356, region_id: 12, name: "Тарутино", translit: "tarutino"},
  {city_id: 357, region_id: 12, name: "Татарбунари", translit: "tatarbunari"},
  {city_id: 635, region_id: 12, name: "Теплодар", translit: "teplodar"},
  {city_id: 358, region_id: 12, name: "Фрунзовка", translit: "frunzovka"},
  {city_id: 359, region_id: 12, name: "Ширяево", translit: "shiryaevo"},
  {city_id: 643, region_id: 12, name: "Южный", translit: "Yujnuy"},
  {city_id: 360, region_id: 20, name: "Великая Багачка", translit: "velikaya_bagachka"},
  {city_id: 361, region_id: 20, name: "Гадяч", translit: "gadyach"},
  {city_id: 362, region_id: 20, name: "Глобино", translit: "globino"},
  {city_id: 363, region_id: 20, name: "Гребенка", translit: "grebenka"},
  {city_id: 364, region_id: 20, name: "Диканька", translit: "dikanka"},
  {city_id: 365, region_id: 20, name: "Зеньков", translit: "zenkov"},
  {city_id: 366, region_id: 20, name: "Карловка", translit: "karlovka"},
  {city_id: 367, region_id: 20, name: "Кобеляки", translit: "kobelyaki"},
  {city_id: 368, region_id: 20, name: "Козельщина", translit: "kozelshina"},
  {city_id: 369, region_id: 20, name: "Комсомольск", translit: "komsomolsk"},
  {city_id: 370, region_id: 20, name: "Котельва", translit: "kotelva"},
  {city_id: 605, region_id: 20, name: "Кременчуг", translit: "kremenchug"},
  {city_id: 373, region_id: 20, name: "Лохвица", translit: "lohvica"},
  {city_id: 374, region_id: 20, name: "Лубны", translit: "lubniy"},
  {city_id: 375, region_id: 20, name: "Машевка", translit: "mashevka"},
  {city_id: 376, region_id: 20, name: "Миргород", translit: "mirgorod"},
  {city_id: 377, region_id: 20, name: "Новые Санжары", translit: "noviye_sanjariy"},
  {city_id: 378, region_id: 20, name: "Оржица", translit: "jrjica"},
  {city_id: 379, region_id: 20, name: "Пирятин", translit: "piryatin"},
  {city_id: 20, region_id: 20, name: "Полтава", translit: "poltava"},
  {city_id: 382, region_id: 20, name: "Решетиловка", translit: "reshetilovka"},
  {city_id: 383, region_id: 20, name: "Семеновка", translit: "semenovka"},
  {city_id: 384, region_id: 20, name: "Хорол", translit: "horol"},
  {city_id: 385, region_id: 20, name: "Чернухи", translit: "chernuhi"},
  {city_id: 386, region_id: 20, name: "Чутово", translit: "chutovo"},
  {city_id: 387, region_id: 20, name: "Шишаки", translit: "shishaki"},
  {city_id: 618, region_id: 21, name: "Алупка", translit: "Alupka"},
  {city_id: 570, region_id: 21, name: "Алушта", translit: "alushta"},
  {city_id: 583, region_id: 21, name: "Бахчисарай", translit: "bahchisarayi"},
  {city_id: 596, region_id: 21, name: "Белогорск", translit: "belogorsk"},
  {city_id: 620, region_id: 21, name: "Гурзуф", translit: "Gurzuf"},
  {city_id: 600, region_id: 21, name: "Джанкой", translit: "djankoyi"},
  {city_id: 589, region_id: 21, name: "Евпатория", translit: "evpatoriya"},
  {city_id: 29, region_id: 21, name: "Керчь", translit: "kerch"},
  {city_id: 598, region_id: 21, name: "Кировское", translit: "kirovskoe"},
  {city_id: 616, region_id: 21, name: "Коктебель", translit: "Koktebel"},
  {city_id: 595, region_id: 21, name: "Красногвардейское", translit: "krasnogvardeyiskoe"},
  {city_id: 585, region_id: 21, name: "Красноперекопск", translit: "krasnoperekopsk"},
  {city_id: 586, region_id: 21, name: "Ленино", translit: "lenino"},
  {city_id: 627, region_id: 21, name: "Мисхор", translit: "Mishor"},
  {city_id: 571, region_id: 21, name: "Нижнегорский", translit: "nijnegorskiyi"},
  {city_id: 630, region_id: 21, name: "Николаевка", translit: "Nikolayevka"},
  {city_id: 591, region_id: 21, name: "Первомайское", translit: "pervomayiskoe"},
  {city_id: 582, region_id: 21, name: "Раздольное", translit: "razdolnoe"},
  {city_id: 584, region_id: 21, name: "Саки", translit: "saki"},
  {city_id: 593, region_id: 21, name: "Севастополь", translit: "sevastopol"},
  {city_id: 21, region_id: 21, name: "Симферополь", translit: "simferopol"},
  {city_id: 587, region_id: 21, name: "Советский", translit: "sovetskiyi"},
  {city_id: 588, region_id: 21, name: "Судак", translit: "sudak"},
  {city_id: 26, region_id: 21, name: "Феодосия", translit: "feodosiya"},
  {city_id: 592, region_id: 21, name: "Черноморское", translit: "chernomorskoe"},
  {city_id: 594, region_id: 21, name: "Ялта", translit: "yalta"},
  {city_id: 388, region_id: 9, name: "Березно", translit: "berezno"},
  {city_id: 389, region_id: 9, name: "Владимирец", translit: "vladimirec"},
  {city_id: 390, region_id: 9, name: "Гоща", translit: "gosha"},
  {city_id: 391, region_id: 9, name: "Демидовка", translit: "demidovka"},
  {city_id: 392, region_id: 9, name: "Дубно", translit: "dubno"},
  {city_id: 393, region_id: 9, name: "Дубровица", translit: "dubrovica"},
  {city_id: 394, region_id: 9, name: "Заречное", translit: "zarechnoe"},
  {city_id: 395, region_id: 9, name: "Здолбунов", translit: "zdolbunov"},
  {city_id: 396, region_id: 9, name: "Корец", translit: "korec"},
  {city_id: 397, region_id: 9, name: "Костополь", translit: "kostopol"},
  {city_id: 398, region_id: 9, name: "Кузнецовск", translit: "kuznecovsk"},
  {city_id: 399, region_id: 9, name: "Млынов", translit: "mliynov"},
  {city_id: 400, region_id: 9, name: "Острог", translit: "jstrog"},
  {city_id: 401, region_id: 9, name: "Радивилов", translit: "radivilov"},
  {city_id: 404, region_id: 9, name: "Ракитное", translit: "rokitnoe"},
  {city_id: 9, region_id: 9, name: "Ровно", translit: "rovno"},
  {city_id: 405, region_id: 9, name: "Сарны", translit: "sarniy"},
  {city_id: 416, region_id: 8, name: "Ахтырка", translit: "ahtiyrka"},
  {city_id: 406, region_id: 8, name: "Белополье", translit: "belopole"},
  {city_id: 407, region_id: 8, name: "Бурынь", translit: "buriyn"},
  {city_id: 408, region_id: 8, name: "Великая Писаревка", translit: "velikaya_pisarevka"},
  {city_id: 409, region_id: 8, name: "Глухов", translit: "gluhov"},
  {city_id: 410, region_id: 8, name: "Конотоп", translit: "konotop"},
  {city_id: 411, region_id: 8, name: "Краснополье", translit: "krasnopole"},
  {city_id: 412, region_id: 8, name: "Кролевец", translit: "krolevec"},
  {city_id: 413, region_id: 8, name: "Лебедин", translit: "lebedin"},
  {city_id: 414, region_id: 8, name: "Липовая Долина", translit: "lipovaya_dolina"},
  {city_id: 415, region_id: 8, name: "Недригайлов", translit: "nedrigayilov"},
  {city_id: 417, region_id: 8, name: "Путивль", translit: "putivl"},
  {city_id: 418, region_id: 8, name: "Ромны", translit: "romniy"},
  {city_id: 419, region_id: 8, name: "Середина-Буда", translit: "seredina-buda"},
  {city_id: 8, region_id: 8, name: "Сумы", translit: "sumiy"},
  {city_id: 422, region_id: 8, name: "Тростянец", translit: "trostyanec"},
  {city_id: 423, region_id: 8, name: "Шостка", translit: "shostka"},
  {city_id: 424, region_id: 8, name: "Ямполь", translit: "yampol"},
  {city_id: 425, region_id: 3, name: "Бережаны", translit: "berejaniy"},
  {city_id: 426, region_id: 3, name: "Борщев", translit: "borshev"},
  {city_id: 427, region_id: 3, name: "Бучач", translit: "buchach"},
  {city_id: 428, region_id: 3, name: "Гусятин", translit: "gusyatin"},
  {city_id: 429, region_id: 3, name: "Залещики", translit: "zaleshiki"},
  {city_id: 430, region_id: 3, name: "Збараж", translit: "zbaraj"},
  {city_id: 431, region_id: 3, name: "Зборов", translit: "zborov"},
  {city_id: 432, region_id: 3, name: "Козова", translit: "kozova"},
  {city_id: 433, region_id: 3, name: "Кременец", translit: "kremenec"},
  {city_id: 434, region_id: 3, name: "Лановцы", translit: "lanovciy"},
  {city_id: 435, region_id: 3, name: "Монастыриска", translit: "monastiyriska"},
  {city_id: 436, region_id: 3, name: "Подволочиск", translit: "podvolochinsk"},
  {city_id: 437, region_id: 3, name: "Подгайцы", translit: "podgayiciy"},
  {city_id: 438, region_id: 3, name: "Теребовля", translit: "terebovlya"},
  {city_id: 3, region_id: 3, name: "Тернополь", translit: "ternopol"},
  {city_id: 441, region_id: 3, name: "Чертков", translit: "chertkov"},
  {city_id: 442, region_id: 3, name: "Шумское", translit: "shumskoe"},
  {city_id: 443, region_id: 7, name: "Балаклея", translit: "balakleya"},
  {city_id: 444, region_id: 7, name: "Барвенково", translit: "barvenkovo"},
  {city_id: 445, region_id: 7, name: "Близнюки", translit: "bliznyuki"},
  {city_id: 446, region_id: 7, name: "Богодухов", translit: "bogoduhov"},
  {city_id: 447, region_id: 7, name: "Боровая", translit: "borovaya"},
  {city_id: 448, region_id: 7, name: "Валки", translit: "valki"},
  {city_id: 449, region_id: 7, name: "Великий Бурлук", translit: "velikiyi_burluk"},
  {city_id: 450, region_id: 7, name: "Волчанск", translit: "volchansk"},
  {city_id: 451, region_id: 7, name: "Двуреченское", translit: "dvurechenskoe"},
  {city_id: 452, region_id: 7, name: "Дергачи", translit: "dergachi"},
  {city_id: 453, region_id: 7, name: "Зачепиловка", translit: "zachepilovka"},
  {city_id: 454, region_id: 7, name: "Змиев", translit: "zmiev"},
  {city_id: 455, region_id: 7, name: "Золочев", translit: "zolochev"},
  {city_id: 456, region_id: 7, name: "Изюм", translit: "izyum"},
  {city_id: 457, region_id: 7, name: "Кегичевка", translit: "kegichevka"},
  {city_id: 458, region_id: 7, name: "Коломак", translit: "kolomak"},
  {city_id: 459, region_id: 7, name: "Красноград", translit: "krasnograd"},
  {city_id: 460, region_id: 7, name: "Краснокутск", translit: "krasnokutsk"},
  {city_id: 461, region_id: 7, name: "Купянск", translit: "kupyansk"},
  {city_id: 462, region_id: 7, name: "Лозовая", translit: "lozovaya"},
  {city_id: 634, region_id: 7, name: "Люботин", translit: "lubotun"},
  {city_id: 463, region_id: 7, name: "Новая Водолага", translit: "novaya_vodolaga"},
  {city_id: 464, region_id: 7, name: "Первомайский", translit: "pervomayiskiyi"},
  {city_id: 465, region_id: 7, name: "Печенеги", translit: "pechenegi"},
  {city_id: 466, region_id: 7, name: "Сахновщина", translit: "sahnovshina"},
  {city_id: 7, region_id: 7, name: "Харьков", translit: "harkov"},
  {city_id: 469, region_id: 7, name: "Чугуев", translit: "chuguev"},
  {city_id: 470, region_id: 7, name: "Шевченково", translit: "shevchenkovo"},
  {city_id: 472, region_id: 23, name: "Белозерка", translit: "belozerka"},
  {city_id: 471, region_id: 23, name: "Берислав", translit: "berislav"},
  {city_id: 474, region_id: 23, name: "Великая Александровка", translit: "velikaya_aleksandrovka"},
  {city_id: 473, region_id: 23, name: "Великая Лепетиха", translit: "velikaya_lepetiha"},
  {city_id: 475, region_id: 23, name: "Верхний Рогачик", translit: "verhniyi_rogachik"},
  {city_id: 476, region_id: 23, name: "Высокополье", translit: "viysokopole"},
  {city_id: 477, region_id: 23, name: "Геническ", translit: "genichesk"},
  {city_id: 478, region_id: 23, name: "Голая Пристань", translit: "golaya_pristan"},
  {city_id: 479, region_id: 23, name: "Горностаевка", translit: "gornostaevka"},
  {city_id: 624, region_id: 23, name: "Железный Порт", translit: "Zelezny Port"},
  {city_id: 480, region_id: 23, name: "Ивановка", translit: "ivanovka"},
  {city_id: 481, region_id: 23, name: "Каланчак", translit: "kalanchak"},
  {city_id: 482, region_id: 23, name: "Каховка", translit: "kahovka"},
  {city_id: 483, region_id: 23, name: "Нижние Серогозы", translit: "nijnie_serogoziy"},
  {city_id: 484, region_id: 23, name: "Новая Каховка", translit: "novaya_kahovka"},
  {city_id: 485, region_id: 23, name: "Нововоронцовка", translit: "novovoroncovka"},
  {city_id: 486, region_id: 23, name: "Новотроицкое", translit: "novotroickoe"},
  {city_id: 487, region_id: 23, name: "Скадовск", translit: "skadovsk"},
  {city_id: 23, region_id: 23, name: "Херсон", translit: "herson"},
  {city_id: 489, region_id: 23, name: "Цюрупинск", translit: "cyurupinsk"},
  {city_id: 490, region_id: 23, name: "Чаплинка", translit: "chaplinka"},
  {city_id: 491, region_id: 4, name: "Белогорье", translit: "belogore"},
  {city_id: 492, region_id: 4, name: "Виньковцы", translit: "vinkovciy"},
  {city_id: 493, region_id: 4, name: "Волочиск", translit: "volochinsk"},
  {city_id: 494, region_id: 4, name: "Городок", translit: "gorodok"},
  {city_id: 495, region_id: 4, name: "Деражня", translit: "derajnya"},
  {city_id: 496, region_id: 4, name: "Дунаевцы", translit: "dunaevciy"},
  {city_id: 497, region_id: 4, name: "Изяслав", translit: "izyaslav"},
  {city_id: 498, region_id: 4, name: "Каменец-Подольский", translit: "kamenec-podolskiyi"},
  {city_id: 499, region_id: 4, name: "Красилов", translit: "krasilov"},
  {city_id: 500, region_id: 4, name: "Летичев", translit: "letichev"},
  {city_id: 501, region_id: 4, name: "Нетешин", translit: "neteshin"},
  {city_id: 502, region_id: 4, name: "Новая Ушица", translit: "novaya_ushica"},
  {city_id: 503, region_id: 4, name: "Полонное", translit: "polonnoe"},
  {city_id: 504, region_id: 4, name: "Славута", translit: "slavuta"},
  {city_id: 506, region_id: 4, name: "Старая Синява", translit: "staraya_sinyava"},
  {city_id: 505, region_id: 4, name: "Староконстантинов", translit: "starokonstantinov"},
  {city_id: 507, region_id: 4, name: "Теофиполь", translit: "teofipol"},
  {city_id: 4, region_id: 4, name: "Хмельницкий", translit: "hmelnickiy"},
  {city_id: 510, region_id: 4, name: "Чемеровцы", translit: "chemerovciy"},
  {city_id: 511, region_id: 4, name: "Шепетовка", translit: "shepetovka"},
  {city_id: 512, region_id: 4, name: "Ярмолинцы", translit: "yarmolinciy"},
  {city_id: 645, region_id: 24, name: "Ватутино", translit: "Vatutino"},
  {city_id: 513, region_id: 24, name: "Городище", translit: "gorodishe"},
  {city_id: 514, region_id: 24, name: "Драбов", translit: "drabov"},
  {city_id: 515, region_id: 24, name: "Жашков", translit: "jashkov"},
  {city_id: 516, region_id: 24, name: "Звенигородка", translit: "zvenigorodka"},
  {city_id: 517, region_id: 24, name: "Золотоноша", translit: "zolotonosha"},
  {city_id: 518, region_id: 24, name: "Каменка", translit: "kamenka"},
  {city_id: 519, region_id: 24, name: "Канев", translit: "kanev"},
  {city_id: 520, region_id: 24, name: "Катеринополь", translit: "katerinopol"},
  {city_id: 521, region_id: 24, name: "Корсунь-Шевченковский", translit: "korsun-shevchenkovskiyi"},
  {city_id: 522, region_id: 24, name: "Лысянка", translit: "liysyanka"},
  {city_id: 523, region_id: 24, name: "Маньковка", translit: "mankovka"},
  {city_id: 524, region_id: 24, name: "Монастырище", translit: "monastiyrishe"},
  {city_id: 525, region_id: 24, name: "Смела", translit: "smela"},
  {city_id: 526, region_id: 24, name: "Тальное", translit: "talnoe"},
  {city_id: 527, region_id: 24, name: "Умань", translit: "uman"},
  {city_id: 528, region_id: 24, name: "Христиновка", translit: "hristinovka"},
  {city_id: 24, region_id: 24, name: "Черкассы", translit: "cherkassiy"},
  {city_id: 532, region_id: 24, name: "Чернобай", translit: "chernobayi"},
  {city_id: 531, region_id: 24, name: "Чигирин", translit: "chigirin"},
  {city_id: 533, region_id: 24, name: "Шпола", translit: "shpola"},
  {city_id: 546, region_id: 6, name: "Бахмач", translit: "bahmach"},
  {city_id: 547, region_id: 6, name: "Бобровица", translit: "bobrovica"},
  {city_id: 548, region_id: 6, name: "Борзна", translit: "borzna"},
  {city_id: 549, region_id: 6, name: "Варва", translit: "varva"},
  {city_id: 550, region_id: 6, name: "Городня", translit: "gorodnya"},
  {city_id: 551, region_id: 6, name: "Ичня", translit: "ichnya"},
  {city_id: 552, region_id: 6, name: "Козелец", translit: "kozelec"},
  {city_id: 553, region_id: 6, name: "Короп", translit: "korop"},
  {city_id: 554, region_id: 6, name: "Корюковка", translit: "koryukovka"},
  {city_id: 555, region_id: 6, name: "Куликовка", translit: "kulikovka"},
  {city_id: 556, region_id: 6, name: "Мена", translit: "mena"},
  {city_id: 557, region_id: 6, name: "Нежин", translit: "nejin"},
  {city_id: 558, region_id: 6, name: "Новгород-Северский", translit: "novgorod-severskiyi"},
  {city_id: 559, region_id: 6, name: "Носовка", translit: "nosovka"},
  {city_id: 560, region_id: 6, name: "Прилуки", translit: "priluki"},
  {city_id: 561, region_id: 6, name: "Репки", translit: "repki"},
  {city_id: 562, region_id: 6, name: "Семеновка", translit: "semenovka"},
  {city_id: 563, region_id: 6, name: "Сосница", translit: "sosnica"},
  {city_id: 564, region_id: 6, name: "Сребное", translit: "srebnoe"},
  {city_id: 565, region_id: 6, name: "Талалаевка", translit: "talalaevka"},
  {city_id: 6, region_id: 6, name: "Чернигов", translit: "chernigov"},
  {city_id: 568, region_id: 6, name: "Щорс", translit: "shors"},
  {city_id: 534, region_id: 25, name: "Вижница", translit: "vijnica"},
  {city_id: 535, region_id: 25, name: "Герца", translit: "gerca"},
  {city_id: 536, region_id: 25, name: "Глубокая", translit: "glubokaya"},
  {city_id: 537, region_id: 25, name: "Заставна", translit: "zastavna"},
  {city_id: 538, region_id: 25, name: "Кельменцы", translit: "kelmenciy"},
  {city_id: 539, region_id: 25, name: "Кицмань", translit: "kicman"},
  {city_id: 647, region_id: 25, name: "Новоднестровск", translit: "Novodnestrovsk"},
  {city_id: 540, region_id: 25, name: "Новоселица", translit: "novoselica"},
  {city_id: 541, region_id: 25, name: "Путила", translit: "putila"},
  {city_id: 542, region_id: 25, name: "Сокиряны", translit: "sokiryaniy"},
  {city_id: 543, region_id: 25, name: "Сторожинец", translit: "storojinec"},
  {city_id: 544, region_id: 25, name: "Хотин", translit: "hotin"},
  {city_id: 25, region_id: 25, name: "Черновцы", translit: "chernovciy"}
])
=begin
District.create!([
  {city_id: 10, area_id: 15186, name: "Святошинский", level: 1},
  {city_id: 10, area_id: 15185, name: "Соломенский", level: 1},
  {city_id: 10, area_id: 15949, name: "Троещина", level: 1},
  {city_id: 10, area_id: 15190, name: "Шевченковский", level: 1},
  {city_id: 10, area_id: 17420, name: "Борщаговка", level: 1},
  {city_id: 10, area_id: 15184, name: "Голосеевский", level: 1},
  {city_id: 10, area_id: 15181, name: "Дарницкий", level: 1},
  {city_id: 10, area_id: 15183, name: "Деснянский", level: 1},
  {city_id: 10, area_id: 15182, name: "Днепровский", level: 1},
  {city_id: 10, area_id: 15187, name: "Оболонский", level: 1},
  {city_id: 10, area_id: 15189, name: "Печерский", level: 1},
  {city_id: 10, area_id: 15188, name: "Подольский", level: 1}
])


Microdistrict.create!([
		                 {district_id: 101, name: "Академгородок", level: 4, area_id: 15186},
		                 {district_id: 102, name: "Беличи", level: 4, area_id: 15186},
		                 {district_id: 103, name: "Березняки", level: 4, area_id: 15182},
		                 {district_id: 104, name: "Бортничи", level: 4, area_id: 15181},
		                 {district_id: 105, name: "Борщаговка", level: 4, area_id: 15186},
		                 {district_id: 106, name: "Ветряные Горы", level: 4, area_id: 15188},
		                 {district_id: 107, name: "Виноградарь", level: 4, area_id: 15188},
		                 {district_id: 108, name: "Воскресенка", level: 4, area_id: 15182},
		                 {district_id: 109, name: "Галаганы", level: 4, area_id: 15186},
		                 {district_id: 110, name: "Голосеево", level: 4, area_id: 15184},
		                 {district_id: 111, name: "ДВРЗ", level: 4, area_id: 15182},
		                 {district_id: 112, name: "Комсомольский", level: 4, area_id: 15182},
		                 {district_id: 113, name: "Кудрявец", level: 4, area_id: 15190},
		                 {district_id: 114, name: "Куреневка", level: 4, area_id: 15187},
		                 {district_id: 115, name: "Левобережный массив", level: 4, area_id: 15182},
		                 {district_id: 116, name: "Лесной", level: 4, area_id: 15183},
		                 {district_id: 117, name: "Липки", level: 4, area_id: 15189},
		                 {district_id: 118, name: "Лукьяновка", level: 4, area_id: 15190},
		                 {district_id: 119, name: "Минский массив", level: 4, area_id: 15187},
		                 {district_id: 120, name: "Мостицкий массив", level: 4, area_id: 15188},
		                 {district_id: 121, name: "Нивки", level: 4, area_id: 15190},
		                 {district_id: 122, name: "Новое строение", level: 4, area_id: 15190},
		                 {district_id: 123, name: "Оболонь", level: 4, area_id: 15187},
		                 {district_id: 124, name: "Осокорки", level: 4, area_id: 15181},
		                 {district_id: 125, name: "Отрадный", level: 4, area_id: 15185},
		                 {district_id: 126, name: "Печерск", level: 4, area_id: 15189},
		                 {district_id: 127, name: "Подол", level: 4, area_id: 15188},
		                 {district_id: 128, name: "Позняки", level: 4, area_id: 15181},
		                 {district_id: 129, name: "Пуща-Водица", level: 4, area_id: 15187},
		                 {district_id: 130, name: "Русановка", level: 4, area_id: 15182},
		                 {district_id: 131, name: "Саперная Слободка", level: 4, area_id: 15184},
		                 {district_id: 132, name: "Святошино", level: 4, area_id: 15186},
		                 {district_id: 133, name: "Соломенка", level: 4, area_id: 15185},
		                 {district_id: 134, name: "Соцгород", level: 4, area_id: 15182},
		                 {district_id: 135, name: "Старый Киев", level: 4, area_id: 15190},
		                 {district_id: 136, name: "Сырец", level: 4, area_id: 15190},
		                 {district_id: 137, name: "Татарка", level: 4, area_id: 15190},
		                 {district_id: 138, name: "Теремки", level: 4, area_id: 15184},
		                 {district_id: 139, name: "Троещина", level: 4, area_id: 15183},
		                 {district_id: 140, name: "Харьковский", level: 4, area_id: 15181},
		                 {district_id: 141, name: "Чёрная гора", level: 4, area_id: 15189},
		                 {district_id: 142, name: "Шулявка", level: 4, area_id: 15190},
		                 {district_id: 143, name: "Дарница", level: 4, area_id: 15181}
                 ])
=end